"""
Auto-generated by Build Agent
Original: mir100_client/models/post_wifi_connection.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.PostWifiConnection")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: mir100_client
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

# coding: utf-8

"""
    MIR100 Rest Interface

    Automatically converted from v270 pdf  # noqa: E501

    OpenAPI spec version: 2.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PostWifiConnection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'address': 'str',
        'device': 'str',
        'dns': 'str',
        'gateway': 'str',
        'netmask': 'str',
        'security': 'str',
        'ssid': 'str'
    }

    attribute_map = {
        'address': 'address',
        'device': 'device',
        'dns': 'dns',
        'gateway': 'gateway',
        'netmask': 'netmask',
        'security': 'security',
        'ssid': 'ssid'
    }

    def __init__(self, address=None, device=None, dns=None, gateway=None, netmask=None, security=None, ssid=None):  # noqa: E501
        """PostWifiConnection - a model defined in Swagger"""  # noqa: E501
        self._address = None
        self._device = None
        self._dns = None
        self._gateway = None
        self._netmask = None
        self._security = None
        self._ssid = None
        self.discriminator = None
        if address is not None:
            self.address = address
        if device is not None:
            self.device = device
        if dns is not None:
            self.dns = dns
        if gateway is not None:
            self.gateway = gateway
        if netmask is not None:
            self.netmask = netmask
        if security is not None:
            self.security = security
        self.ssid = ssid

    @property
    def address(self):
        print("[UNILAB] PostWifiConnection.__init__() called", flush=True)
        """Gets the address of this PostWifiConnection.  # noqa: E501


        :return: The address of this PostWifiConnection.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.address() called")
        """Sets the address of this PostWifiConnection.


        :param address: The address of this PostWifiConnection.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def device(self):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.device() called")
        """Gets the device of this PostWifiConnection.  # noqa: E501


        :return: The device of this PostWifiConnection.  # noqa: E501
        :rtype: str
        """
        return self._device

    @device.setter
    def device(self, device):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.device() called")
        """Sets the device of this PostWifiConnection.


        :param device: The device of this PostWifiConnection.  # noqa: E501
        :type: str
        """

        self._device = device

    @property
    def dns(self):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.dns() called")
        """Gets the dns of this PostWifiConnection.  # noqa: E501


        :return: The dns of this PostWifiConnection.  # noqa: E501
        :rtype: str
        """
        return self._dns

    @dns.setter
    def dns(self, dns):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.dns() called")
        """Sets the dns of this PostWifiConnection.


        :param dns: The dns of this PostWifiConnection.  # noqa: E501
        :type: str
        """

        self._dns = dns

    @property
    def gateway(self):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.gateway() called")
        """Gets the gateway of this PostWifiConnection.  # noqa: E501


        :return: The gateway of this PostWifiConnection.  # noqa: E501
        :rtype: str
        """
        return self._gateway

    @gateway.setter
    def gateway(self, gateway):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.gateway() called")
        """Sets the gateway of this PostWifiConnection.


        :param gateway: The gateway of this PostWifiConnection.  # noqa: E501
        :type: str
        """

        self._gateway = gateway

    @property
    def netmask(self):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.netmask() called")
        """Gets the netmask of this PostWifiConnection.  # noqa: E501


        :return: The netmask of this PostWifiConnection.  # noqa: E501
        :rtype: str
        """
        return self._netmask

    @netmask.setter
    def netmask(self, netmask):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.netmask() called")
        """Sets the netmask of this PostWifiConnection.


        :param netmask: The netmask of this PostWifiConnection.  # noqa: E501
        :type: str
        """

        self._netmask = netmask

    @property
    def security(self):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.security() called")
        """Gets the security of this PostWifiConnection.  # noqa: E501


        :return: The security of this PostWifiConnection.  # noqa: E501
        :rtype: str
        """
        return self._security

    @security.setter
    def security(self, security):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.security() called")
        """Sets the security of this PostWifiConnection.


        :param security: The security of this PostWifiConnection.  # noqa: E501
        :type: str
        """

        self._security = security

    @property
    def ssid(self):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.ssid() called")
        """Gets the ssid of this PostWifiConnection.  # noqa: E501


        :return: The ssid of this PostWifiConnection.  # noqa: E501
        :rtype: str
        """
        return self._ssid

    @ssid.setter
    def ssid(self, ssid):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.ssid() called")
        """Sets the ssid of this PostWifiConnection.


        :param ssid: The ssid of this PostWifiConnection.  # noqa: E501
        :type: str
        """
        if ssid is None:
            raise ValueError("Invalid value for `ssid`, must not be `None`")  # noqa: E501

        self._ssid = ssid

    def to_dict(self):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.to_dict() called")
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostWifiConnection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.to_str() called")
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.__repr__() called")
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.__eq__() called")
        """Returns true if both objects are equal"""
        if not isinstance(other, PostWifiConnection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        _unilab_logger.debug("[UNILAB] PostWifiConnection.__ne__() called")
        """Returns true if both objects are not equal"""
        return not self == other

__all__ = ["PostWifiConnection"]
