"""
Auto-generated by Build Agent
Original: PYME/ParallelTasks/taskQueue.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.TaskQueue")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: PYME
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))



##################
# taskQueue.py
#
# Copyright David Baddeley, 2009
# d.baddeley@auckland.ac.nz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##################

import time
import threading

CHUNKSIZE = 50

def doNix(taskQueue): #do nothing
    pass

def popZero(workerN, NWorkers, NTasks): #give worker oldest task irrespective of which worker called
    return 0

class TaskQueue:
    def __init__(self, name, initialTasks=[], onEmpty = doNix, fTaskToPop = popZero):
        print("[UNILAB] TaskQueue.__init__() called", flush=True)
        #Pyro.core.ObjBase.__init__(self)
        #self.name = name
        self.queueID = name
        self.openTasks = list(initialTasks)
        self.closedTasks = []
        self.tasksInProgress = []
        self.onEmpty = onEmpty #function to call when queue is empty
        self.fTaskToPop = fTaskToPop #function to call to decide which task to give a worker (useful if the workers need to have share information with, e.g., previous tasks as this can improve eficiency of per worker buffering of said info).
        self.inProgressLock = threading.Lock()

    def postTask(self,task):
        _unilab_logger.debug("[UNILAB] TaskQueue.postTask() called")
        self.openTasks.append(task)
        #print '[%s] - Recieved new task' % self.queueID

    def postTasks(self,tasks):
        _unilab_logger.debug("[UNILAB] TaskQueue.postTasks() called")
        self.openTasks += tasks
        #print '[%s] - Recieved %d new tasks' % (self.queueID, len(tasks))

    def getTask(self, workerN = 0, NWorkers = 1):
        _unilab_logger.debug("[UNILAB] TaskQueue.getTask() called")
        """get task from front of list, blocks"""
        #print 'Task requested'
        while len(self.openTasks) < 1:
            time.sleep(0.01)

        task = self.openTasks.pop(self.fTaskToPop(workerN, NWorkers, len(self.openTasks)))

        task.queueID = self.queueID
        task.initializeWorkerTimeout(time.time())
        with self.inProgressLock:
            self.tasksInProgress.append(task)
        
        #print '[%s] - Task given to worker' % self.queueID
        return task

    def getTasks(self, workerN = 0, NWorkers = 1):
        _unilab_logger.debug("[UNILAB] TaskQueue.getTasks() called")
        return [self.getTask(workerN, NWorkers) for i in range(min(CHUNKSIZE,len(self.openTasks)))]

    def returnCompletedTask(self, taskResult):
        _unilab_logger.debug("[UNILAB] TaskQueue.returnCompletedTask() called")
        with self.inProgressLock:
                for it in self.tasksInProgress[:]:
                        if (it.taskID == taskResult.taskID):
                                self.tasksInProgress.remove(it)
            
            
        self.fileResult(taskResult)

        if (len(self.openTasks) + len(self.tasksInProgress)) == 0: #no more tasks
                    self.onEmpty(self)
            

    def returnCompletedTasks(self, taskResults):
        _unilab_logger.debug("[UNILAB] TaskQueue.returnCompletedTasks() called")
        with self.inProgressLock:
            for taskResult in taskResults:
                for it in self.tasksInProgress[:]:
                    if (it.taskID == taskResult.taskID):
                        self.tasksInProgress.remove(it)
        
        
        #for taskResult in taskResults:
        #allow this to be over-ridden 
        self.fileResults(taskResults)

        if (len(self.openTasks) + len(self.tasksInProgress)) == 0: #no more tasks
            self.onEmpty(self)
        

    def fileResults(self, taskResults):
        _unilab_logger.debug("[UNILAB] TaskQueue.fileResults() called")
        #allow this to be over-ridden in derived classes to file multiple results at once
        for taskResult in taskResults:
            self.fileResult(taskResult)
    
    def fileResult(self,taskResult):
        _unilab_logger.debug("[UNILAB] TaskQueue.fileResult() called")
        self.closedTasks.append(taskResult)

    def getCompletedTask(self):
        _unilab_logger.debug("[UNILAB] TaskQueue.getCompletedTask() called")
        if len(self.closedTasks) < 1:
            return None
        else:
            return self.closedTasks.pop(0)

    def checkTimeouts(self):
        _unilab_logger.debug("[UNILAB] TaskQueue.checkTimeouts() called")
        with self.inProgressLock:
            curTime = time.time()
            for it in self.tasksInProgress:
                if 'workerTimeout' in dir(it):
                    if curTime > it.workerTimeout:
                        self.openTasks.insert(0, it)
                        self.tasksInProgress.remove(it)
        

    def getNumberOpenTasks(self, exact=True):
        _unilab_logger.debug("[UNILAB] TaskQueue.getNumberOpenTasks() called")
        return len(self.openTasks)

    def getNumberTasksInProgress(self):
        _unilab_logger.debug("[UNILAB] TaskQueue.getNumberTasksInProgress() called")
        return len(self.tasksInProgress)

    def getNumberTasksCompleted(self):
        _unilab_logger.debug("[UNILAB] TaskQueue.getNumberTasksCompleted() called")
        return len(self.closedTasks)

    def cleanup(self):
        _unilab_logger.debug("[UNILAB] TaskQueue.cleanup() called")
        pass

    def purge(self):
        _unilab_logger.debug("[UNILAB] TaskQueue.purge() called")
        self.openTasks = []
        self.closedTasks = []
        self.tasksInProgress = []

    def setPopFcn(self, fcn):
        _unilab_logger.debug("[UNILAB] TaskQueue.setPopFcn() called")
        """ sets the function which determines which task to give a worker"""
        self.fTaskToPop = fcn


class TaskQueueWithData(TaskQueue):
    def __init__(self, name, initialTasks=[], onEmpty = doNix, fTaskToPop = popZero):
        print("[UNILAB] TaskQueue.__init__() called", flush=True)
        TaskQueue.__init__(self, name, initialTasks, onEmpty, fTaskToPop)

        self.data = {}

    def getTasks(self, workerN = 0, NWorkers = 1):
        _unilab_logger.debug("[UNILAB] TaskQueue.getTasks() called")
        return [self.getTask(workerN, NWorkers)]

    def getQueueData(self, fieldName, *args):
        _unilab_logger.debug("[UNILAB] TaskQueue.getQueueData() called")
        """Get data, defined by fieldName and potntially additional arguments,  ascociated with queue"""

        return self.data[fieldName]

    def setQueueData(self, fieldName, value):
        _unilab_logger.debug("[UNILAB] TaskQueue.setQueueData() called")
        """Get data, defined by fieldName and potntially additional arguments,  ascociated with queue"""

        self.data[fieldName] = value

__all__ = ["TaskQueue"]
