"""
Auto-generated by Build Agent
Original: hardwarelibrary/communication/diagnostics.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.USBDeviceDescription")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: hardwarelibrary, hardwarelibrary
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

import usb.core
import usb.util
from hardwarelibrary.communication.usbport import *
from os import listdir, stat, system
from stat import *
from os.path import isfile, join, exists, isfile
import re
from typing import NamedTuple

class USBParameters(NamedTuple):
    configuration : int = None
    interface: int = 0
    alternate: int = 0
    outputEndpoint : int = None
    inputEndpoint : int = None    

class DeviceCommand(NamedTuple):
    text : str = None
    data : bytearray = None
    reply: str = None
    replyData: bytearray = None
    replyDataLength: int = 0
    actualReply = None
  
class USBDeviceDescription:
    @classmethod

    def __init__(self, name, idVendor=None, idProduct=None):
        print("[UNILAB] USBDeviceDescription.__init__() called", flush=True)
        self.name = name
        self.idVendor = idVendor
        self.idProduct = idProduct

        self._serialPort = None
        self.regexPOSIXPort = "Nothing"

        self._usbPort = None
        self.usbParameters = None
        self.deviceCommands = []
        self.mustAssertTrue = []
        self.mustAssertFalse = []
        self.catchExceptions = False
        
    @property
    def isVisible(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.isVisible() called")
        return self.isVisibleOnUSBHub or self.isVisibleAsPOSIXPort

    @property
    def isVisibleOnUSBHub(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.isVisibleOnUSBHub() called")
        dev = usb.core.find(idVendor=self.idVendor, idProduct=self.idProduct)
        if dev is None:
            raise RuntimeError("Device not visible on USB")

        isVisible = dev is not None
        usb.util.dispose_resources(dev)
        return isVisible

    def diagnoseConnectivity(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.diagnoseConnectivity() called")
        import subprocess
        isPhysicallyConnectedAndTurnedOn = []
        try:
            try:
                response = self.isVisibleOnUSBHub
            except:
                response = False
            isPhysicallyConnectedAndTurnedOn.append(response)

            response = subprocess.check_output(['ioreg', '-n"{0}"'.format(self.name), '-r'])
            if len(response) == 0:
                print("⚠️  Using ioreg, the device does not appear connected under the name '{0}'".format(self.name))
                isPhysicallyConnectedAndTurnedOn.append(False)

            if self.hasUniquePOSIXPortMatch:
                print("❓  This is surprising, because it appears visible in {0}".format(self.bsdPath))
                print("❓  The name used for matching in ioreg may be wrongly configured: {0}".format(self.name))                    
                isPhysicallyConnectedAndTurnedOn = None
            elif len(self.bsdPathMatches) > 1:
                print("⚠️  Unable to find a unique matching port in /dev/: {0}".format(self.bsdPathMatches))
                print("    It appears more than 1 devices match the POSIX path-regex '{0}'".format(self.regexPOSIXPort))
                isPhysicallyConnectedAndTurnedOn = None
            elif len(self.bsdPathMatches) == 0:
                isPhysicallyConnectedAndTurnedOn = False
                print("‼️  After other checks (/dev/ and ioreg): the device is not physically connected or off")
            else:
                isPhysicallyConnectedAndTurnedOn = True
        except Exception as err:
            print("Unable to complete connectivity diagnosis : {0}".format(err))

    @property
    def isVisibleAsPOSIXPort(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.isVisibleAsPOSIXPort() called")
        if self.hasUniquePOSIXPortMatch:
            return True
        else:
            raise RuntimeError("POSIX path does not exist: {0}".format(self.bsdPath))
        return False

    @property
    def isValidPOSIXPath(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.isValidPOSIXPath() called")
        if not exists(self.bsdPath):
            raise RuntimeError("POSIX path does not exist: {0}".format(self.bsdPath))

        mode = stat(self.bsdPath).st_mode
        if not S_ISCHR(mode):
            raise RuntimeError("POSIX path is not a character device: {0}".format(self.bsdPath))            
        
        return True
    
    @property
    def isVisibleAsPOSIXPort(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.isVisibleAsPOSIXPort() called")
        if self.hasUniquePOSIXPortMatch:
            if not exists(self.bsdPath):
                raise RuntimeError("POSIX path does not exist: {0}".format(self.bsdPath))
            permissions = stat(self.bsdPath)
            return True
        else:
            raise RuntimeError("POSIX path does not exist: {0}".format(self.bsdPath))
        return False

    @property
    def hasUniquePOSIXPortMatch(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.hasUniquePOSIXPortMatch() called")
        return len(self.bsdPathMatches) == 1

    @property
    def bsdPath(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.bsdPath() called")
        if self.hasUniquePOSIXPortMatch:
            return self.bsdPathMatches[0]
        return None

    @property
    def bsdPathMatches(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.bsdPathMatches() called")
        prog = re.compile(self.regexPOSIXPort)
        
        matches = []
        for path in listdir("/dev"):
            if prog.match(path):
                matches.append("/dev/{0}".format(path))

        return matches

    @property
    def portCanBeOpened(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.portCanBeOpened() called")
        return self.usbPortCanBeOpened or self.posixPortCanBeOpened
    
    @property
    def usbPortCanBeOpened(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.usbPortCanBeOpened() called")
        if self.usbParameters is not None:
            dev = None
            intf = None
            try:
                dev = usb.core.find(idVendor=self.idVendor, idProduct=self.idProduct)
                if dev is None:
                    raise RuntimeError("Cannot find device with usb.core")

                dev.set_configuration()
                conf = dev.get_active_configuration()
                if conf is None:
                    raise RuntimeError("Cannot configure device")
                intf = conf[(self.usbParameters.interface,self.usbParameters.alternate)]
                outputEndpoint = intf[self.usbParameters.outputEndpoint]            
                inputEndpoint = intf[self.usbParameters.inputEndpoint]
                return True
            except Exception as err:
                raise err
            finally:
                if dev is not None:
                    if intf is not None:
                        usb.util.release_interface(dev, intf)
                    usb.util.dispose_resources(dev)

        return False

    @property
    def usbPort(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.usbPort() called")
        if self._usbPort is None:
            self._usbPort = USBPort(idVendor=self.idVendor, 
                                    idProduct=self.idProduct, 
                                    interfaceNumber=self.usbParameters.interface, 
                                    defaultEndPoints=(self.usbParameters.outputEndpoint, 
                                        self.usbParameters.inputEndpoint) )

        return self._usbPort
 
    @property
    def posixPort(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.posixPort() called")
        if not self.hasUniquePOSIXPortMatch:
            return None
        
        if self._serialPort is None:
            self._serialPort = SerialPort(bsdPath=self.bsdPath)

        return self._serialPort
    
    @property
    def posixPortCanBeOpened(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.posixPortCanBeOpened() called")
        if self.posixPort is None:
            return False

        isOpen = False
        try:
            self.posixPort.open()
            isOpen = self.posixPort.isOpen
        except Exception as err:
            raise err
        finally:
            self.posixPort.close()

        return isOpen

    @property
    def canReadWritePOSIXCommands(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.canReadWritePOSIXCommands() called")
        self.posixPort.open()
        self.posixPort.flush()

        try:
            for command in self.deviceCommands:
                if command.text is not None:
                    bytesWritten = self.posixPort.writeString(command.text)
                    if bytesWritten != len(command.text):
                        return False
                elif command.data is not None:
                    bytesWritten = self.posixPort.writeData(command.data)
                    if bytesWritten != len(command.data):
                        return False

                if command.reply is not None:
                    reply = self.posixPort.readString()
                    if reply != command.reply:
                        return False
                elif command.replyData is not None:
                    replyData = self.posixPort.readData(length=len(command.replyData))
                    if replyData != command.replyData:
                        return False

        except Exception as err:
            raise err
            return False
        finally:
            self.posixPort.close()

        return True

    @property
    def canReadWriteUSBCommands(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.canReadWriteUSBCommands() called")
        port = self.usbPort

        results = []
        if len(self.deviceCommands) == 0:
            return False

        success = True
        try:
            print("Testing {0} commands.".format( len(self.deviceCommands)))
            for command in self.deviceCommands:
                try:
                    if command.text is not None:
                        bytesWritten = port.writeString(command.text)
                        if bytesWritten != len(command.text):
                            success = False
                    elif command.data is not None:
                        bytesWritten = port.writeData(command.data)
                        if bytesWritten != len(command.data):
                            success = False

                    if command.reply is not None:
                        reply = port.readString()
                        if reply != command.reply:
                            success = False
                    elif command.replyData is not None:
                        print("Now")
                        if command.replyDataLength != 0:
                            replyData = port.readData(length=command.replyDataLength)
                        print(replyData, command.replyData)
                        if replyData != command.replyData:
                            success = False

                    results.append(success)
                except Exception as err:
                    print("NOt make it {0}".format(err))
                    results.append(False)

        except Exception as err:
            success = False

        for res, command in zip(results, self.deviceCommands):
            print(" {0} for {1}".format(res, command))
        return success

    def assertTrue(self, property):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.assertTrue() called")
        try:
            value = getattr(self, property)
            if value:
                print("✅ {0} is True".format(property))
            else:
                print("🚫 {0} is not True".format(property))
        except Exception as err:
            print("🚫 {0} failed: {1}".format(property, err))

    def assertFalseOrRaise(self, property):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.assertFalseOrRaise() called")
        try:
            value = getattr(self, property)
            if not value:
                print("✅ NOT {0} is True".format(property))
            else:
                print("🚫 NOT {0} is not True".format(property))
        except Exception as err:
            print("✅ NOT {0} is True [Exception: {1}]".format(property, err))

    def assertRaise(self, property):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.assertRaise() called")
        try:
            value = getattr(self, property)
            if not value:
                print("✅ {0}".format(property))
            else:
                print("🚫 !{0}".format(property))
        except Exception as err:
            print("✅ {0} failed as expected: {1}".format(property, err))

    def assertEqual(self, property, expectation):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.assertEqual() called")
        try:
            value = getattr(self, property)
            if value == expectation:
                print("✅ {0} == {1}".format(property, expectation))
            else:
                print("🚫 {0} != {1}".format(property, expectation))
        except Exception as err:
            print("🚫 {0} failed: {1}".format(property, err))


    def assertNotEqual(self, property, expectation):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.assertNotEqual() called")
        try:
            value = getattr(self, property)
            if value != expectation:
                print("✅ {0} != {1}".format(property, expectation))
            else:
                print("🚫 {0} == {1}".format(property, expectation))
        except Exception as err:
            print("🚫 {0} failed: {1}".format(property, err))

    def report(self):
        _unilab_logger.debug("[UNILAB] USBDeviceDescription.report() called")
        print("============================================================")
        print("Diagnostic report for device {0} [vid 0x{1:04x} pid 0x{2:04x}]".format(self.name, self.idVendor, self.idProduct))
        print("============================================================")
        for key, value in self.__dict__.items():
            if key[0] == "_":
                continue # private
            print("{0} = {1}".format(key, value))

        print("------------------------------------------------------------")
        for property in self.mustAssertTrue:
            self.assertTrue(property)
        for property in self.mustAssertFalse:
            self.assertFalseOrRaise(property)

def tellMeMore(idVendor=None, idProduct=None):
    devices = connectedUSBDevices(idVendor=idVendor, idProduct=idProduct)

    for device in devices:
        print(device)

def connectedUSBDevices(idVendor=None, idProduct=None, serialNumber=None):
    """ Return a list of USB devices that are currently
    connected. If idProduct is provided, match only these
    products. If a serial number is provided, return the matching device otherwise
    return  an empty list. If no serial number is provided, return all devices.

    Parameters
    ----------
    idProduct: int Default: None
        The USB idProduct to match
    serialNumber: str Default: None
        The serial number to match, when there are still more than one device after
        filtering out the idProduct.  If there is a single match, the serial number
        is disregarded.

    Returns
    -------

    devices: list of Device
        A list of connected devices matching the criteria provided
    """

    if idProduct is None and idVendor is None:
        devices = list(usb.core.find(find_all=True))
    elif idProduct is None:
        devices = list(usb.core.find(find_all=True, idVendor=idVendor))
    else:
        devices = list(usb.core.find(find_all=True, 
                                idVendor=idVendor, 
                                idProduct=idProduct))

    # Remove Apple Devices
    devices = [device for device in devices if device.idVendor != 0x05ac]
    
    if serialNumber is not None: # A serial number was provided, try to match
        for device in devices:
            deviceSerialNumber = usb.util.get_string(device, device.iSerialNumber ) 
            if deviceSerialNumber == serialNumber:
                return [device]

        return [] # Nothing matched

    return devices


if __name__ == '__main__':

    dev = USBDeviceDescription("Optotune LD", idVendor=0x03eb, idProduct=0x2018)
    dev.regexPOSIXPort = None
    dev.usbParameters = USBParameters(configuration=0, 
                                      interface=0,
                                      alternate=0,
                                      outputEndpoint=0,
                                      inputEndpoint=1)
    dev.mustAssertTrue = ['isVisible', 'isVisibleOnUSBHub','isVisibleAsPOSIXPort',
                          'isValidPOSIXPath','posixPortCanBeOpened', 'hasUniquePOSIXPortMatch', 
                          'usbPortCanBeOpened', 'canReadWritePOSIXCommands',
                          'canReadWriteUSBCommands']
    dev.mustAssertFalse = []
    
    dev.deviceCommands.append(DeviceCommand(text='Start',reply='Ready\r\n'))
    dev.deviceCommands.append(DeviceCommand(data=b'\x50\x77\x44\x41\x07\xd0\x00\x00\x31\xfd'))
#    dev.deviceCommands.append(DeviceCommand(data=b'\x50\x77\x44\x41\x07\xd0\x00\x00\x31\xfd', replyData='\x00'))

    #dev.usbPort.open()
    # print(dev.__dict__)
    dev.diagnoseConnectivity()
#    dev.report()

__all__ = ["USBDeviceDescription"]
