"""
Auto-generated by Build Agent
Original: PYME/Acquire/Hardware/olympusix81.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.OlympusIX81HalogenLamp")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: PYME, PYME
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

"""
Control the halogen lamp (transmitted light) on an Olympus IX81 stand.

Uses the serial command set described at https://madhadron.com/science/olympus_ix81_commands.html

TODO - move logic to an IX81 class which also allows control of other stand features and support more of the command set.
TODO - some form of error handling
TODO - consider re-writing the query function to try and match responses to commands (these are not guaranteed to be synchronous) 

"""
import serial
import time
import threading
from PYME.Acquire.Hardware.lasers import Laser

class OlympusIX81HalogenLamp(Laser):
    def __init__(self, name, portname='COM17', turn_on=False, **kwargs):
        print("[UNILAB] OlympusIX81HalogenLamp.__init__() called", flush=True)
        self.ser_port = serial.Serial(portname, 19200, parity='E',
                                      timeout=2, writeTimeout=2)
        self.lock = threading.Lock()
        self.name = name
        self.powerControlable = False
        self.isOn = False
        #self.TurnOn()
        Laser.__init__(self, name, turn_on, **kwargs)

    def _query(self, command, lines_expected=1):
        _unilab_logger.debug("[UNILAB] OlympusIX81HalogenLamp._query() called")
        with self.lock:
            self.ser_port.reset_input_buffer()
            self.ser_port.write(command)
            reply = [self.ser_port.readline() for line in range(lines_expected)]
            self.ser_port.reset_input_buffer()
        return reply

    def IsOn(self):
        _unilab_logger.debug("[UNILAB] OlympusIX81HalogenLamp.IsOn() called")
        return self.isOn
        
    def TurnOn(self):
        _unilab_logger.debug("[UNILAB] OlympusIX81HalogenLamp.TurnOn() called")
        # make sure serial is open
        try:
            self.ser_port.open()
        except serial.SerialException:
            pass

        self.isOn = True

        # turn on the laser
        self._query(b'1LOG IN\r\n', lines_expected=1)
        self._query(b'1LMPSW ON\r\n', lines_expected=1)
        self._query(b'1LOG OUT\r\n', lines_expected=1)
        #self.ser_port.flush()

    def TurnOff(self):
        _unilab_logger.debug("[UNILAB] OlympusIX81HalogenLamp.TurnOff() called")
        self._query(b'1LOG IN\r\n', lines_expected=1)
        self._query(b'1LMPSW OFF\r\n', lines_expected=1)
        self._query(b'1LOG OUT\r\n', lines_expected=1)
        #self.ser_port.flush()
        self.isOn = False

__all__ = ["OlympusIX81HalogenLamp"]
