"""
Auto-generated by Build Agent
Original: src/labtoolkit/Positioner/ETS2090.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.ETS2090")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: labtoolkit, labtoolkit
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

from labtoolkit.Instrument import Instrument
from time import sleep


class ETS2090(Instrument):
    """.
    
    Also EMCO 2090.
    """
    # *OPC? returns immediately 0 moving 1 complete
    
    def __init__(self, *args, **kwargs):
        print("[UNILAB] ETS2090.__init__() called", flush=True)
        super().__init__(*args, **kwargs)
    def __post__(self):
        _unilab_logger.debug("[UNILAB] ETS2090.__post__() called")
        self.inst.read_termination = '\r\n'
        self.inst.write_termination = '\r\n'
        self.write('N2')  # Set numeric mode 2 (2090 -- xxx.x) 

    def moving(self):
        _unilab_logger.debug("[UNILAB] ETS2090.moving() called")
        # Hardware, rarely, passes back a number in the -hundreds
        # self.query_bool('*OPC?')   
        return '1' != self.query('*OPC?')

    @property
    def device_type(self):
        _unilab_logger.debug("[UNILAB] ETS2090.device_type() called")
        """."""
        return self.query('TYP?')

    @property
    def limit_upper(self):
        _unilab_logger.debug("[UNILAB] ETS2090.limit_upper() called")
        """."""
        return self.query_float('UL?')

    @limit_upper.setter
    def limit_upper(self, upper_limit):
        _unilab_logger.debug("[UNILAB] ETS2090.limit_upper() called")
        self.write(f'UL {upper_limit}')
    
    @property
    def limit_lower(self):
        _unilab_logger.debug("[UNILAB] ETS2090.limit_lower() called")
        """."""
        return self.query_float('LL?')

    @limit_lower.setter
    def limit_lower(self, lower_limit):
        _unilab_logger.debug("[UNILAB] ETS2090.limit_lower() called")
        self.write(f'LL {lower_limit}')
    
    @property
    def polarization(self):
        _unilab_logger.debug("[UNILAB] ETS2090.polarization() called")
        """."""
        # 0 vert, 1 horiz
        return 'Vert' if self.query_int('P?') == 0 else 'Horiz'

    @polarization.setter
    def polarization(self, polarization):
        _unilab_logger.debug("[UNILAB] ETS2090.polarization() called")
        if polarization == 'Horiz':
            self.write(f'PH')
        if polarization == 'Vert':
            self.write(f'PV')
        
    def sweep_up(self):
        _unilab_logger.debug("[UNILAB] ETS2090.sweep_up() called")
        """Not yet tested."""
        return self.write('UP')
    
    def sweep_down(self):
        _unilab_logger.debug("[UNILAB] ETS2090.sweep_down() called")
        """Not yet tested."""
        return self.write('DW')

    def target_seek(self):
        _unilab_logger.debug("[UNILAB] ETS2090.target_seek() called")
        """."""
        # self.write(f'SK {target}')
        self.write('SK')

    @property
    def target(self):
        _unilab_logger.debug("[UNILAB] ETS2090.target() called")
        """."""
        return self.query_float('TG?')

    @target.setter
    def target(self, target):
        _unilab_logger.debug("[UNILAB] ETS2090.target() called")
        self.write(f'TG {target}')
        
    @property
    def position(self):
        _unilab_logger.debug("[UNILAB] ETS2090.position() called")
        """."""
        return self.query_float('CP')
    
    
    @property
    def local(self):
        _unilab_logger.debug("[UNILAB] ETS2090.local() called")
        """Return to local control."""
        return self.write('RTL')  # works as expected
    
    def sequence(self, sequence=[400,100]*2):
        _unilab_logger.debug("[UNILAB] ETS2090.sequence() called")
        """."""
        for step, height in enumerate(sequence):
            self.target = height
            self.target_seek()

            while self.moving():
                print(f'Not done {step}/{len(sequence)}, current {self.position} cm')
                sleep(1)
        self.local

__all__ = ["ETS2090"]
