"""
Auto-generated by Build Agent
Original: src/labtoolkit/Positioner/AnaheimAutomationSMC40.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.AnaheimAutomationSMC40")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: labtoolkit, labtoolkit
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

from labtoolkit.Instrument import Instrument
from time import sleep


class AnaheimAutomationSMC40(Instrument):

    # http://www.anaheimautomation.com/manuals/stepper/L010098%20-%20SMC40%20Users%20Guide.pdf

    def __init__(self, *args, **kwargs):
        print("[UNILAB] AnaheimAutomationSMC40.__init__() called", flush=True)
        super().__init__(*args, **kwargs)
    @property
    def heading(self):
        _unilab_logger.debug("[UNILAB] AnaheimAutomationSMC40.heading() called")
        return NotImplemented

    @heading.setter
    def heading(self, clockwise=True):
        _unilab_logger.debug("[UNILAB] AnaheimAutomationSMC40.heading() called")
        if clockwise is True:
            self.write('D+')  # Clockwise
        else:
            self.write('D-')  # Anti-Clockwise

    @property
    def stepangle(self):
        _unilab_logger.debug("[UNILAB] AnaheimAutomationSMC40.stepangle() called")
        return NotImplemented

    @stepangle.setter
    def stepangle(self, stepangle=1):  # 100 is 1 degree
        self.write(f'XMN{int(stepangle * 100)}')
        # int(Q_(stepangle, 'degree').magnitude * 100)
        # self.write('XMN{}'.format(int(Q_(stepangle, 'degree').magnitude * 100)))

    def zero(self):
        _unilab_logger.debug("[UNILAB] AnaheimAutomationSMC40.stepangle() called")
        self.write('XGH')

    def init(self):
        _unilab_logger.debug("[UNILAB] AnaheimAutomationSMC40.init() called")
        self.write('@0')

    def IDN(self):
        _unilab_logger.debug("[UNILAB] AnaheimAutomationSMC40.IDN() called")
        return self.query('ID')

    def WAI(self):
        _unilab_logger.debug("[UNILAB] AnaheimAutomationSMC40.WAI() called")
        return self.query('XMC')  # ??

    def TRG(self):
        _unilab_logger.debug("[UNILAB] AnaheimAutomationSMC40.TRG() called")
        self.write('XGR')

    def move(self, clockwise=True, angle=1, wait=True):
        _unilab_logger.debug("[UNILAB] AnaheimAutomationSMC40.move() called")
        self.stepsize = angle
        self.heading = clockwise
        self.write('XGR')
        if wait is True:
            self.WAI()

'''
import serial
from serial.tools import list_ports

	
for each in list_ports.comports():
    print('{}\t\t{}'.format(each.device, each.description))
port = input('Serial Port? : ')
# port = 'COM7'

with serial.Serial(port, 9600, timeout=1, bytesize=8, parity='N', stopbits=1) as ser:
    while ser.isOpen():
        ser.write(b'ID')
        print(ser.readline())
        # self.write('XMN{}'.format(int(stepsize*100)))  # 100 is 1 degree
        # self.write('D+')  # Clockwise
        # self.write('D-')  # Anti-Clockwise
        # self.write('XGH')  # Go Home
        # self.write('@0')  # Init?
        # 'XMC'  # Complete?
        
'''

__all__ = ["AnaheimAutomationSMC40"]
