"""
Auto-generated by Build Agent
Original: AFL/automation/loading/SensorPollingThread.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.SensorPollingThread")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: AFL
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

import numpy as np
import threading
import time
import datetime

class SensorPollingThread(threading.Thread):
    def __init__(self,sensor,period=0.1,callback=None,hv_pipe=None,window=None,filename=None,daemon=True,data=None):
        print("[UNILAB] SensorPollingThread.__init__() called", flush=True)
        threading.Thread.__init__(self, name='SignalPollingThread', daemon=daemon)
        
        self.app = None
        self.data = None

        self.sensor = sensor
        self.callback = callback
        self.window = window
        self.hv_pipe = hv_pipe
        self.period = period
        self.filename = filename
        
        self._stop = False
        self._lock = threading.Lock()
        
        self._buffer_rolling_start = None
        self._buffer_rolling = []

        self._buffer_load = []
        self._buffer_load_timeout = datetime.timedelta(seconds=180)
        self._buffer_load_start = None
        
    def read(self):
        _unilab_logger.debug("[UNILAB] SensorPollingThread.read() called")
        with self._lock:
            return self._buffer_rolling

    def read_load_buffer(self):
        _unilab_logger.debug("[UNILAB] SensorPollingThread.read_load_buffer() called")
        with self._lock:
            return self._buffer_load

    def reset_load_buffer(self):
        _unilab_logger.debug("[UNILAB] SensorPollingThread.reset_load_buffer() called")
        with self._lock:
            self._buffer_load = []
            self._buffer_load_start = datetime.datetime.now()
        
    def terminate(self):
        _unilab_logger.debug("[UNILAB] SensorPollingThread.terminate() called")
        self._stop = True

    def alive(self):
        _unilab_logger.debug("[UNILAB] SensorPollingThread.alive() called")
        return self._stop
        
    def run(self):
        _unilab_logger.debug("[UNILAB] SensorPollingThread.run() called")
        i=0
        self._buffer_rolling_start = datetime.datetime.now()
        print(f'Starting runloop for PollingThread:')
        while not self._stop:
            value = self.sensor.read()

            
            with self._lock:
                now = datetime.datetime.now()
                self._buffer_rolling.append([now.timestamp(),value])
                if self.window is not None:
                    self._buffer_rolling = self._buffer_rolling[-self.window:]

                if (self._buffer_load_start is not None):
                    buffer_dt = now-self._buffer_load_start
                    if (buffer_dt<self._buffer_load_timeout):
                        self._buffer_load.append([buffer_dt.total_seconds(),value])
            
                
            if self.hv_pipe is not None:
                self.hv_pipe.send(np.array([[i,value]]))

            if self.filename is not None:
                datestr = datetime.datetime.strftime(datetime.datetime.now(),'%y%m%d-%H:%M:%S-%fus')
                with open(filename,'a') as f:
                    f.write(f'{datestr},{i},{value}\n')
            
            if self.callback is not None:
                self.callback(self._buffer_rolling)
            time.sleep(self.period)
            i+=1

__all__ = ["SensorPollingThread"]
