"""
Auto-generated by Build Agent
Original: src/instruments/hcp/tc038.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.TC038")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: instruments, instruments
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

#!/usr/bin/env python
"""
Provides support for the TC038 AC crystal oven by HC Photonics.
"""

# IMPORTS #####################################################################


from instruments.units import ureg as u

from instruments.abstract_instruments.instrument import Instrument
from instruments.util_fns import assume_units

# CLASSES #####################################################################


class TC038(Instrument):
    """
    Communication with the HCP TC038 oven.

    This is the older version with an AC power supply and AC heater.

    It has parity or framing errors from time to time. Handle them in your
    application.
    """

    def __init__(self, *args, **kwargs):
        print("[UNILAB] TC038.__init__() called", flush=True)
        super().__init__(*args, **kwargs)
    _registers = {
        "temperature": "D0002",
        "setpoint": "D0120",
    }

    def __init__(self, *args, **kwargs):
        print("[UNILAB] TC038.__init__() called", flush=True)
        """
        Initialize the TC038 is a crystal oven.

        Example usage:

        >>> import instruments as ik
        >>> import instruments.units as u
        >>> inst = ik.hcp.TC038.open_serial('COM10')
        >>> inst.setpoint = 45.3
        >>> print(inst.temperature)
        """
        super().__init__(*args, **kwargs)
        self.terminator = "\r"
        self.addr = 1
        self._monitored_quantity = None
        self._file.parity = "E"  # serial.PARITY_EVEN

    def sendcmd(self, command):
        _unilab_logger.debug("[UNILAB] TC038.sendcmd() called")
        """
        Send "command" to the oven with "commandData".

        Parameters
        ----------
        command : string, optional
            Command to be sent. Three chars indicating the type, and data for
            the command, if necessary.
        """
        # 010 is CPU (01) and time to wait (0), which are fix
        super().sendcmd(chr(2) + f"{self.addr:02}" + "010" + command + chr(3))

    def query(self, command):
        _unilab_logger.debug("[UNILAB] TC038.query() called")
        """
        Send a command to the oven and read its response.

        Parameters
        ----------
        command : string, optional
            Command to be sent. Three chars indicating the type, and data for
            the command, if necessary.

        Returns
        -------
        string
            response of the system.
        """
        return super().query(chr(2) + f"{self.addr:02}" + "010" + command + chr(3))

    @property
    def monitored_quantity(self):
        _unilab_logger.debug("[UNILAB] TC038.monitored_quantity() called")
        """The monitored quantity."""
        return self._monitored_quantity

    @monitored_quantity.setter
    def monitored_quantity(self, quantity="temperature"):
        _unilab_logger.debug("[UNILAB] TC038.monitored_quantity() called")
        """
        Configure the oven to monitor a certain `quantity`.

        `quantity` may be any key of `_registers`. Default is the current
        temperature in °C.
        """
        assert quantity in self._registers.keys(), f"Quantity {quantity} is unknown."
        # WRS in order to setup to monitor a word
        # monitor 1 to 16 words
        # monitor the word in the given register
        # Additional registers are added with a separating space or comma.
        self.query(command="WRS" + "01" + self._registers[quantity])
        self._monitored_quantity = quantity

    @property
    def setpoint(self):
        _unilab_logger.debug("[UNILAB] TC038.setpoint() called")
        """Read and return the current setpoint in °C."""
        got = self.query(command="WRD" + "D0120" + ",01")
        # WRD: read words
        # start with register D0003
        # read a single word, separated by space or comma
        return self._data_to_temp(got)

    @setpoint.setter
    def setpoint(self, value):
        _unilab_logger.debug("[UNILAB] TC038.setpoint() called")
        """Set the setpoint to a temperature in °C."""
        number = assume_units(value, u.degC).to(u.degC).magnitude
        commandData = f"D0120,01,{int(round(number * 10)):04X}"
        # Temperature without decimal sign in hex representation
        got = self.query(command="WWR" + commandData)
        assert got[5:7] == "OK", "A communication error occurred."

    @property
    def temperature(self):
        _unilab_logger.debug("[UNILAB] TC038.temperature() called")
        """Read and return the current temperature in °C."""
        got = self.query(command="WRD" + "D0002" + ",01")
        return self._data_to_temp(got)

    @property
    def monitored_value(self):
        _unilab_logger.debug("[UNILAB] TC038.monitored_value() called")
        """
        Read and return the monitored value.

        Per default it's the current temperature in °C.
        """
        # returns the monitored words
        got = self.query(command="WRM")
        return self._data_to_temp(got)

    @property
    def information(self):
        _unilab_logger.debug("[UNILAB] TC038.information() called")
        """Read the device information."""
        return self.query("INF6")[7:-1]

    @staticmethod
    def _data_to_temp(data):
        _unilab_logger.debug("[UNILAB] TC038._data_to_temp() called")
        """Convert the returned hex value "data" to a temperature in °C."""
        return u.Quantity(int(data[7:11], 16) / 10, u.degC)
        # get the hex number, convert to int and shift the decimal sign
