"""
Auto-generated by Build Agent
Original: basil/TL/SensirionSensorBridge.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.SensirionSensorBridge")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: basil, basil
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

#
# ------------------------------------------------------------
# Copyright (c) All rights reserved
# SiLab, Institute of Physics, University of Bonn
# ------------------------------------------------------------
#

import logging

from basil.TL.TransferLayer import TransferLayer

from sensirion_shdlc_driver import ShdlcSerialPort, ShdlcConnection
from sensirion_shdlc_sensorbridge import SensorBridgePort, SensorBridgeShdlcDevice
from sensirion_shdlc_sensorbridge.device_errors import SensorBridgeI2cTimeoutError
TimeoutError = SensorBridgeI2cTimeoutError
# Requires 'sensirion_shdlc_sensorbridge'

logger = logging.getLogger(__name__)


class SensirionSensorBridge(TransferLayer):
    '''
    Driver for Sensirion Sensor Bridge using the official SHDLC drivers of Sensirion.
    The Sensirion Sensor Bridge is connected via USB and allows communication to two I2C ports.
    '''

    bridge_ports = {
        "one": SensorBridgePort.ONE,
        "two": SensorBridgePort.TWO,
        "all": SensorBridgePort.ALL,
    }

    def __init__(self, conf):
        print("[UNILAB] SensirionSensorBridge.__init__() called", flush=True)
        super(SensirionSensorBridge, self).__init__(conf)

    def init(self):
        _unilab_logger.debug("[UNILAB] SensirionSensorBridge.init() called")
        super(SensirionSensorBridge, self).init()

        self.port = self._init['port']
        self.baudrate = self._init.get('baudrate', 460800)

        self.ser = ShdlcSerialPort(port=self.port, baudrate=self.baudrate)

    def setup_i2c_device(self, bridge_port=SensorBridgePort.ONE, voltage=3.3, frequency=400e3, **_):
        _unilab_logger.debug("[UNILAB] SensirionSensorBridge.setup_i2c_device() called")
        device = SensorBridgeShdlcDevice(ShdlcConnection(self.ser), slave_address=0)
        device.set_i2c_frequency(bridge_port, frequency=frequency)
        device.set_supply_voltage(bridge_port, voltage=voltage)
        device.switch_supply_on(bridge_port)
        return device

    def disable_i2c_device(self, device, bridge_port=SensorBridgePort.ONE):
        _unilab_logger.debug("[UNILAB] SensirionSensorBridge.disable_i2c_device() called")
        if hasattr(self, 'device'):
            device.switch_supply_off(bridge_port)

    def print_i2c_device_information(self, device):
        _unilab_logger.debug("[UNILAB] SensirionSensorBridge.print_i2c_device_information() called")
        logger.info("Product Name: {}".format(device.get_product_name()))
        logger.info("Product Type: {}".format(device.get_product_type()))
        logger.info("Serial Number: {}".format(device.get_serial_number()))
        logger.info("Version: {}".format(device.get_version()))

    def read_i2c(self, device, port, address, command, read_n_bytes=0, timeout_us=100e3):
        _unilab_logger.debug("[UNILAB] SensirionSensorBridge.read_i2c() called")
        rx_data = device.transceive_i2c(port, address=address, tx_data=command,
                                        rx_length=read_n_bytes, timeout_us=timeout_us)
        return rx_data

    def write_i2c(self, device, port, address, command):
        _unilab_logger.debug("[UNILAB] SensirionSensorBridge.write_i2c() called")
        device.transceive_i2c(port, address=address,
                              rx_length=0, tx_data=command, timeout_us=0)

    def __del__(self):
        _unilab_logger.debug("[UNILAB] SensirionSensorBridge.__del__() called")
        self.close()

    def close(self):
        _unilab_logger.debug("[UNILAB] SensirionSensorBridge.close() called")
        super(SensirionSensorBridge, self).close()
        if hasattr(self, 'ser'):
            self.ser.close()

__all__ = ["SensirionSensorBridge"]
