"""
仿真配对 bundle 的 Edge 端编排（Phase 1B Chunk 5b）。

职责：sim/twin 模式启动时收集 graph 真实设备 class → 调后端 resolve →
复用社区包机制下载缺失 virtual package → 编译为 device_pair.generated.yaml +
manifest → 交给 PairRegistry 加载。real 模式不参与。

下载/缓存/sha256 校验复用 community_packages，不另造一套机制。
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

from unilabos.app.community_packages import (
    _dedupe_existing_dirs,
    _ensure_remote_item_cached,
    load_manifest as load_community_manifest,
    save_manifest as save_community_manifest,
)
from unilabos.utils import logger
from unilabos.utils.banner_print import print_status

SIMULATION_PAIRS_DIR = "simulation_pairs"
GENERATED_YAML_FILENAME = "device_pair.generated.yaml"
MANIFEST_FILENAME = "manifest.json"


class SimulationPairError(RuntimeError):
    """sim/twin 启动前的仿真配对致命错误（如 missing_sim_policy=fail 且无 virtual）。"""


@dataclass
class SimulationPairPrepareResult:
    generated_yaml: Optional[str] = None  # device_pair.generated.yaml 绝对路径
    devices_dirs: List[str] = field(default_factory=list)  # 下载的 virtual package 源码目录
    bundle_version: Optional[str] = None
    offline: bool = False


def extract_real_classes(graph_data: Optional[Dict[str, Any]]) -> List[str]:
    """从 graph 节点收集真实设备 class（去重排序），作为 resolve 入参。"""
    if not graph_data:
        return []
    result: List[str] = []
    for node in graph_data.get("nodes", []):
        if not isinstance(node, dict):
            continue
        class_name = node.get("class")
        if isinstance(class_name, str) and class_name:
            result.append(class_name)
    return sorted(set(result))


def compile_bundle_to_yaml(pairs: List[Dict[str, Any]]) -> str:
    """把 bundle pairs 编译为与 Phase 1A PairRegistry 兼容的 device_pair.yaml 文本（§6.4）。"""
    entries: List[Dict[str, Any]] = []
    for pair in pairs:
        entry: Dict[str, Any] = {
            "real": pair.get("real"),
            "virtual": pair.get("virtual"),
            "missing_sim_policy": pair.get("missing_sim_policy", "stub"),
        }
        observed = pair.get("twin_observed")
        if observed:
            entry["twin_observed"] = list(observed)
        if pair.get("twin_throttle_hz") is not None:
            entry["twin_throttle_hz"] = pair["twin_throttle_hz"]
        entries.append(entry)
    header = (
        "# generated by Uni-Lab-OS Edge from Device Square simulation pair bundle\n"
        "# do not edit manually\n"
    )
    return header + yaml.safe_dump({"pairs": entries}, allow_unicode=True, sort_keys=False)


def prepare_simulation_pairs(
    graph_data: Optional[Dict[str, Any]],
    working_dir: str | Path,
    mode: str,
    http_client: Any = None,
    lab_uuid: str = "",
    edge_uuid: str = "",
    unilabos_version: str = "",
    package_locks: Optional[List[Dict[str, Any]]] = None,
) -> SimulationPairPrepareResult:
    """sim/twin 启动编排：resolve → 下载 virtual package → 生成 yaml/manifest。"""
    if mode not in ("sim", "twin"):
        return SimulationPairPrepareResult()
    real_classes = extract_real_classes(graph_data)
    if not real_classes:
        return SimulationPairPrepareResult()

    pairs_dir = _pairs_dir(working_dir)
    generated_yaml_path = pairs_dir / GENERATED_YAML_FILENAME
    manifest_path = pairs_dir / MANIFEST_FILENAME
    graph_hash = _graph_hash(real_classes)

    print_status(f"解析仿真配对：mode={mode} real_classes={real_classes}", "info")
    bundle = _resolve_bundle(
        real_classes, mode, http_client, lab_uuid, edge_uuid, unilabos_version, package_locks
    )

    if bundle is None:
        # §10.3 离线策略：后端不可达 → 兼容缓存优先，否则交还给仓库默认 yaml
        return _offline_fallback(generated_yaml_path, manifest_path, real_classes)

    pairs = [p for p in bundle.get("pairs", []) if isinstance(p, dict)]
    for warning in bundle.get("warnings") or []:
        if isinstance(warning, dict):
            print_status(f"[SimulationPair] {warning.get('real')}: {warning.get('message')}", "warning")

    # §6.4 #4 / §10.3：fail 策略且无 virtual，启动前明确报错
    _assert_no_unsatisfied_fail(pairs)

    devices_dirs = _download_virtual_packages(pairs, working_dir, http_client)

    generated_yaml_path.write_text(compile_bundle_to_yaml(pairs), encoding="utf-8")

    bundle_version = bundle.get("bundle_version")
    manifest = {
        "bundle_version": bundle_version,
        "lab_uuid": lab_uuid,
        "edge_uuid": edge_uuid,
        "graph_hash": graph_hash,
        "real_classes": real_classes,
        "generated_yaml": GENERATED_YAML_FILENAME,
    }
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    if bundle_version:
        (pairs_dir / f"bundle-{_safe_version(bundle_version)}.json").write_text(
            json.dumps(bundle, ensure_ascii=False, indent=2), encoding="utf-8"
        )

    print_status(f"仿真配对 bundle 已编译: {generated_yaml_path} (version={bundle_version})", "info")
    return SimulationPairPrepareResult(
        generated_yaml=str(generated_yaml_path),
        devices_dirs=devices_dirs,
        bundle_version=bundle_version,
    )


def _resolve_bundle(
    real_classes: List[str],
    mode: str,
    http_client: Any,
    lab_uuid: str,
    edge_uuid: str,
    unilabos_version: str,
    package_locks: Optional[List[Dict[str, Any]]],
) -> Optional[Dict[str, Any]]:
    if http_client is None:
        logger.trace("[SimulationPair] 未提供 http_client，跳过远端 resolve，仅用本地缓存")
        return None
    try:
        response = http_client.resolve_simulation_pairs(
            real_classes,
            mode=mode,
            lab_uuid=lab_uuid,
            edge_uuid=edge_uuid,
            package_locks=package_locks,
            unilabos_version=unilabos_version,
        )
        data = response.get("data", response) if isinstance(response, dict) else None
        if isinstance(data, dict) and "pairs" in data:
            logger.trace(
                f"[SimulationPair] resolve 成功: version={data.get('bundle_version')} "
                f"pairs={len(data.get('pairs') or [])}"
            )
            return data
        logger.warning(f"[SimulationPair] resolve 响应缺少 pairs，按离线处理: {response}")
    except Exception as exc:
        logger.warning(f"[SimulationPair] 远端 resolve 失败，尝试本地缓存: {exc}")
    return None


def _offline_fallback(
    generated_yaml_path: Path,
    manifest_path: Path,
    real_classes: List[str],
) -> SimulationPairPrepareResult:
    if generated_yaml_path.exists() and manifest_path.exists():
        try:
            manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        except Exception:
            manifest = {}
        cached_classes = set(manifest.get("real_classes") or [])
        if cached_classes and set(real_classes).issubset(cached_classes):
            print_status(
                f"后端不可达，使用本地仿真配对缓存 (version={manifest.get('bundle_version')})", "warning"
            )
            return SimulationPairPrepareResult(
                generated_yaml=str(generated_yaml_path),
                offline=True,
                bundle_version=manifest.get("bundle_version"),
            )
        print_status("后端不可达且本地缓存 graph class 不兼容，回退仓库默认 device_pair.yaml", "warning")
    else:
        print_status("后端不可达且无本地仿真配对缓存，回退仓库默认 device_pair.yaml", "warning")
    return SimulationPairPrepareResult(offline=True)


def _download_virtual_packages(
    pairs: List[Dict[str, Any]],
    working_dir: str | Path,
    http_client: Any,
) -> List[str]:
    """复用社区包下载/缓存机制，把 bundle 内缺失的 virtual package 落盘并返回源码目录。"""
    community_manifest = load_community_manifest(working_dir)
    dirs: List[str] = []
    for pair in pairs:
        virtual_package = pair.get("virtual_package")
        if not virtual_package:
            continue
        namespace = virtual_package.get("class_namespace")
        if not namespace:
            logger.warning(f"[SimulationPair] virtual_package 缺少 class_namespace，跳过: {virtual_package}")
            continue
        item = {
            "class_namespace": namespace,
            "package_info": {
                "class_namespace": namespace,
                "name": virtual_package.get("normalized_name"),
                "version": virtual_package.get("version"),
                "download_url": virtual_package.get("download_url"),
                "sha256": virtual_package.get("sha256"),
            },
        }
        package_dir = _ensure_remote_item_cached(
            item, working_dir, community_manifest, http_client=http_client
        )
        if package_dir:
            dirs.append(str(package_dir))
    save_community_manifest(working_dir, community_manifest)
    return _dedupe_existing_dirs(dirs)


def _assert_no_unsatisfied_fail(pairs: List[Dict[str, Any]]) -> None:
    failed = [
        p.get("real")
        for p in pairs
        if not p.get("virtual") and p.get("missing_sim_policy") == "fail"
    ]
    if failed:
        raise SimulationPairError(
            "sim/twin 启动失败：以下真实设备无可用 virtual driver 且 missing_sim_policy=fail: "
            + ", ".join(str(x) for x in failed)
        )


def _pairs_dir(working_dir: str | Path) -> Path:
    root = Path(working_dir) / SIMULATION_PAIRS_DIR
    root.mkdir(parents=True, exist_ok=True)
    return root


def _graph_hash(real_classes: List[str]) -> str:
    payload = json.dumps(sorted(real_classes), ensure_ascii=False)
    return "sha256:" + hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _safe_version(version: Any) -> str:
    return "".join(c if c.isalnum() else "" for c in str(version)) or "unknown"
