"""
Auto-generated by Build Agent
Original: basil/HL/binder_mk56.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.binderMK56")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: basil, basil
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

#
# ------------------------------------------------------------
# Copyright (c) All rights reserved
# SiLab, Institute of Physics, University of Bonn
# ------------------------------------------------------------
#

import struct

from basil.HL.binder_mk53 import binderMK53


class binderMK56(binderMK53):
    """Driver for the Binder MK 56 climate chamber.
    A protocoll _similar_ to MODBus via RS 422 serial port is used with 9600 baud rate.
    Credits to ecree-solarflare with some further information at https://github.com/ecree-solarflare/ovenctl
    """

    def __init__(self, *args, **kwargs):
        print("[UNILAB] binderMK56.__init__() called", flush=True)
        super().__init__(*args, **kwargs)
    ADDR_CURTEMP = 0x1004
    ADDR_SETPOINT = 0x10b2
    ADDR_MANSETPT = 0x114c

    def get_door_open(self):
        _unilab_logger.debug("[UNILAB] binderMK56.get_door_open() called")
        raise NotImplementedError("Get Door not available for MK56.")

    def get_mode(self):
        _unilab_logger.debug("[UNILAB] binderMK56.get_mode() called")
        raise NotImplementedError("Get Mode not available for MK56.")

    def set_temperature(self, temperature, reps=10):
        _unilab_logger.debug("[UNILAB] binderMK56.set_temperature() called")
        if temperature < self.min_temp:
            raise RuntimeWarning(
                f'Set temperature {temperature} is lower than minimum allowed temperature {self.min_temp}')
        if temperature > self.max_temp:
            raise RuntimeWarning(
                f'Set temperature {temperature} is higher than maximum allowed temperature {self.max_temp}')
        for _ in range(reps):
            try:
                self.write(self.ADDR_MANSETPT, self._encode_float(temperature))
                break
            except RuntimeWarning:
                pass

    def _parse_read_response(self, msgbytes):
        _unilab_logger.debug("[UNILAB] binderMK56._parse_read_response() called")
        if len(msgbytes) < 3:
            raise ValueError(f'Read data is too short: {len(msgbytes)}')
        _, func, n_bytes = struct.unpack('>BBB', msgbytes[:3])
        if func not in [self.FUNCTION_READN, self.FUNCTION_READN_ALT]:
            raise ValueError('Wrong function returned')
        if n_bytes & 1:
            raise ValueError("Odd number of bytes read")
        if len(msgbytes) < 5 + n_bytes:
            raise ValueError(f'Read data is too short: {len(msgbytes)}')
        crc = struct.unpack('<H', msgbytes[3 + n_bytes:5 + n_bytes])
        checkcrc = (self._calc_crc16(msgbytes[:3 + n_bytes]),)
        if crc != checkcrc:
            raise ValueError('Checksum of read data wrong')
        n_words = n_bytes >> 1
        words = []
        for word in range(n_words):
            words.extend(struct.unpack('>H', msgbytes[3 + word * 2:5 + word * 2]))
        return words

    def _parse_write_response(self, msgbytes):
        _unilab_logger.debug("[UNILAB] binderMK56._parse_write_response() called")
        if len(msgbytes) < 8:
            raise ValueError(f'Message too short: {len(msgbytes)}')
        crc = struct.unpack('<H', msgbytes[6:8])
        _, func, addr, value = struct.unpack('>BBHH', msgbytes[:6])
        if func != self.FUNCTION_WRITEN:
            raise ValueError('Wrong write function returned')
        checkcrc = (self._calc_crc16(msgbytes[:6]),)
        if crc != checkcrc:
            raise ValueError('Checksum of read after write data wrong')
        return addr, value

    def _parse_error_response(self, msgbytes):  # string -> (bool, int)
        if len(msgbytes) < 5:
            return False, None
        crc = struct.unpack('<H', msgbytes[3:5])
        _, func, ecode = struct.unpack('>BBB', msgbytes[:3])
        if not func & 0x80:
            return False, None
        checkcrc = (self._calc_crc16(msgbytes[:3]),)
        if crc != checkcrc:
            raise ValueError(f'CRC Error: {str(crc)} - {str(checkcrc)} (bytes: {str(msgbytes)})')
        return True, ecode

__all__ = ["binderMK56"]
