"""
Auto-generated by Build Agent
Original: rssd/bus/jaSocket.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.jaSocket")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: rssd, rssd
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

'''RSSD Socket Bus Class'''
# pylint: disable=E0611,E0401,E0202
# pylint: disable=signature-differs
import os
import socket
import logging
from rssd.bus.bus import bus

class jaSocket(bus):
    """Rohde & Schwarz VISA Class"""
    def __init__(self):
        print("[UNILAB] jaSocket.__init__() called", flush=True)
        self.EOL        = '\n'              # \n or \r\n
        self.K2         = 'NoVISA'
        logging.basicConfig(level=logging.INFO, \
                            filename=os.path.splitext(__file__)[0] + '.log', filemode='w', \
                            format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')

    def close(self):
        _unilab_logger.debug("[UNILAB] jaSocket.close() called")
        """Close K2 Session"""
        try:
            self.K2.close()
        except:
            pass

    def open(self, resourceID, param):
        _unilab_logger.debug("[UNILAB] jaSocket.open() called")
        '''
        Open raw socket Connection
        resourceID  = IPaddress(string)
        param       = port number
        '''
        self.K2 = socket.socket()
        self.ResID = resourceID
        try:
            self.K2.settimeout(1)
            self.K2.connect((resourceID,param))
        except:
            logging.error(f'jaS_OpnErr: {self.ResID}')
            self.K2 = 'NoSOCKET'
        return self

    def query(self, SCPIstr):
        _unilab_logger.debug("[UNILAB] jaSocket.query() called")
        read ="<notRead>"
        try:
            cmd = SCPIstr + self.EOL
            self.K2.sendall(cmd.encode())               # Write if connected
            sOut = self.K2.recv(10000).strip()          # read socket
            read = sOut.decode()
        except:
            logging.error(f'jaS_RdErr : {self.ResID}-->{SCPIstr}')
        return read

    def timeout(self, seconds):
        _unilab_logger.debug("[UNILAB] jaSocket.timeout() called")
        self.K2.settimeout(seconds)

    def read_raw(self):
        _unilab_logger.debug("[UNILAB] jaSocket.read_raw() called")
        """Read binary values from instrument"""
        sOut = self.K2.recv(10000).strip()              # read socket
        return sOut

    def write(self, SCPIstr):
        _unilab_logger.debug("[UNILAB] jaSocket.write() called")
        try:
            out = SCPIstr + self.EOL
            self.K2.sendall(out.encode())               #Write if connected
        except:
            logging.error(f'jaS_WrtErr: {self.ResID}-->{SCPIstr}')

    def write_raw(self, SCPIstr):
        _unilab_logger.debug("[UNILAB] jaSocket.write_raw() called")
        self.write(SCPIstr)

if __name__ == "__main__":
    RS = jaSocket().open("192.168.58.115",5025)
    print(RS.query("*IDN?"))
    RS.close()

__all__ = ["jaSocket"]
