"""
Auto-generated by Build Agent
Original: hardware/ni_co_hardware.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.NI_CO_hw")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: hardware, devices.ni_co_device
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

from ScopeFoundry import HardwareComponent

from devices.ni_co_device import NI_CO_device

import nidaqmx.system as ni


class NI_CO_hw(HardwareComponent):
    def __init__(self, *args, **kwargs):
        print("[UNILAB] NI_CO_hw.__init__() called", flush=True)
        super().__init__(*args, **kwargs)
    name = 'NI_CO_hw'

    def setup(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.setup() called")
        # create logged quantities, that are related to the graphical interface
        board, terminals, trig = self.update_channels()

        self.devices = self.add_logged_quantity('device', dtype=str, initial=board)
        self.channel1 = self.add_logged_quantity('Ext_exposure', dtype=str, choices=terminals, initial=terminals[0])
        self.high_time1 = self.add_logged_quantity('high_time(exp)', dtype=float, initial=0.5,
                                                   vmin=0.0001,spinbox_decimals=3, unit='s')
        self.low_time1 = self.add_logged_quantity('low_time(exp)', dtype=float, initial=0.47, vmin=0.0001,
                                                  spinbox_decimals=3, unit='s')
        self.channel2 = self.add_logged_quantity('Ext_run', dtype=str, choices=terminals, initial=terminals[1])
        self.high_time2 = self.add_logged_quantity('high_time', dtype=float, initial=1.2, vmin=0.0001,
                                                   spinbox_decimals=3, unit='s')
        self.period2 = self.add_logged_quantity('period', dtype=float, initial=1.250, vmin=0.0001,
                                                spinbox_decimals=3, unit='s')
        self.initial_delay_chan1 = self.add_logged_quantity('initial_delay_chan1', dtype=float, initial=0, vmin=0,
                                                            spinbox_decimals=6, unit='s')
        self.initial_delay_chan2 = self.add_logged_quantity('initial_delay_chan2', dtype=float, initial=0, vmin=0,
                                                            spinbox_decimals=6, unit='s')

        self.trigger = self.add_logged_quantity('trigger', dtype=bool, initial=True)
        self.trigger_source = self.add_logged_quantity('trigger_source', dtype=str, choices=trig, initial=trig[0])
        self.trigger_edge = self.add_logged_quantity('trigger_edge', dtype=str, choices=['rising', 'falling'],
                                                     initial='rising')

        self.add_operation("start_task", self.start)
        self.add_operation("stop_task", self.stop)

    def connect(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.connect() called")
        # continuous_to_constant = {False:10178, True:10123} #create a dictionary for mapping the mode with the corresponding constants in nidaqmx

        # open connection to hardware
        self.channel1.change_readonly(True)
        self.channel2.change_readonly(True)

        self.CO_device = NI_CO_device(channel1=self.channel1.val, channel2=self.channel2.val,
                                      initial_delay_chan1=self.initial_delay_chan1.val,
                                      initial_delay_chan2=self.initial_delay_chan2.val,
                                      high_time1=self.high_time1.val, low_time1=self.low_time1.val,
                                      high_time2=self.high_time2.val, period2=self.period2.val,
                                      trigger=self.trigger.val, trigger_source=self.trigger_source.val,
                                      trigger_edge=self.trigger_edge.val, debug=self.debug_mode.val)

        # connect logged quantities
        self.initial_delay_chan1.hardware_set_func = self.CO_device.set_initial_delay_chan1
        self.initial_delay_chan2.hardware_set_func = self.CO_device.set_initial_delay_chan2
        self.high_time1.hardware_set_func = self.CO_device.set_high_time1
        self.low_time1.hardware_set_func = self.CO_device.set_low_time1
        self.high_time2.hardware_set_func = self.CO_device.set_high_time2
        self.period2.hardware_set_func = self.CO_device.set_period2
        self.trigger.hardware_set_func = self.CO_device.set_trigger
        self.trigger_source.hardware_set_func = self.CO_device.set_trigger_source
        self.trigger_edge.hardware_set_func = self.CO_device.set_trigger_edge

        self.initial_delay_chan1.hardware_read_func = self.get_initial_delay_chan1
        self.initial_delay_chan2.hardware_read_func = self.get_initial_delay_chan2
        self.high_time1.hardware_read_func = self.get_high_time1
        self.low_time1.hardware_read_func = self.get_low_time1
        self.high_time2.hardware_read_func = self.get_high_time2
        self.period2.hardware_read_func = self.get_period2
        self.trigger.hardware_read_func = self.get_trigger
        self.trigger_source.hardware_read_func = self.get_trigger_source
        self.trigger_edge.hardware_read_func = self.get_trigger_edge

    def disconnect(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.disconnect() called")
        self.channel1.change_readonly(False)
        self.channel2.change_readonly(False)
        # disconnect hardware
        if hasattr(self, 'CO_device'):
            if self.CO_device.task_ni._handle:
                self.CO_device.close()
            del self.CO_device


        for lq in self.settings.as_list():
            lq.hardware_read_func = None
            lq.hardware_set_func = None

    def start(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.start() called")
        # if hasattr(self.CO_device, 'task_ni'):
        #     if self.CO_device.task_ni._handle != None:
        #         print('Current task is not closed yet')
        # else:
        self.CO_device.start_task()

    def stop(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.stop() called")
        print(self.CO_device.task_ni.is_task_done())
        self.CO_device.stop_task()
        if hasattr(self.CO_device.task_ni, '_handle'):
            print(self.CO_device.task_ni._handle)
        else:
            print('no')

    def update_channels(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.update_channels() called")
        ''' Find a NI device and return board + do_terminals + trigger terminals'''
        system = ni.System.local()
        device = system.devices[0]
        board = device.product_type + ' : ' + device.name
        terminals = []
        trig = []
        for line in device.co_physical_chans:
            terminals.append(line.name)
        for j in device.terminals:
            if 'PFI' in j:
                trig.append(j)

        return board, terminals, trig

    def get_initial_delay_chan1(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.get_initial_delay_chan1() called")

        return float("{0:.6f}".format(self.initial_delay_chan1.val))

    def get_initial_delay_chan2(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.get_initial_delay_chan2() called")

        return float("{0:.6f}".format(self.initial_delay_chan2.val))

    def get_high_time1(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.get_high_time1() called")

        return float("{0:.4f}".format(self.high_time1.val))

    def get_low_time1(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.get_low_time1() called")

        return float("{0:.4f}".format(self.low_time1.val))

    def get_high_time2(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.get_high_time2() called")

        return float("{0:.4f}".format(self.high_time2.val))

    def get_period2(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.get_period2() called")

        return float("{0:.4f}".format(self.period2.val))

    def get_trigger(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.get_trigger() called")

        return self.trigger.val

    def get_trigger_source(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.get_trigger_source() called")

        return self.trigger_source.val

    def get_trigger_edge(self):
        _unilab_logger.debug("[UNILAB] NI_CO_hw.get_trigger_edge() called")

        return self.trigger_edge.val

__all__ = ["NI_CO_hw"]
