"""
Auto-generated by Build Agent
Original: PYME/Acquire/Hardware/phoxxLaser.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.PhoxxLaser")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: PYME, PYME
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))



##################
# piezo_e816.py
#
# Copyright David Baddeley, 2009
# d.baddeley@auckland.ac.nz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##################

import serial
import time
import threading

try:
    import Queue
except ImportError:
    import queue as Queue

from PYME.Acquire.Hardware.lasers import Laser

class PhoxxLaser(Laser):
    def __init__(self, name,turnOn=False, portname='COM3', maxpower=0.14, power_fudge=1.0,**kwargs):
        print("[UNILAB] PhoxxLaser.__init__() called", flush=True)
        self.ser_args = dict(port=portname, baudrate=500000, timeout=.1, writeTimeout=2)
        #self.ser_port = serial.Serial(portname, 500000, timeout=.1, writeTimeout=2)
        self.powerControlable = True
        #self.isOn=False
        
        self.doPoll=True
        self.maxpower = maxpower # maximum power, for our current only laser of this type it is 140mW
        # optionally de-rate the maximum power that we can set. Used as a work-around for calibration issues
        # in the built-in power meter which causes the erroneous detection of an over-power failure and triggers
        # and interlock
        self.power_fudge = power_fudge
        self.commandQueue = Queue.Queue()
        self.replyQueue = Queue.Queue()
        #self.adhocQueue = Queue.Queue()
        
        self.adHocVals = {}
        
        self.threadPoll = threading.Thread(target=self._poll)
        self.threadPoll.start()
        
        #self.TurnOff()
        
        #self.power = self._getOutputPower()
        time.sleep(1)
        self.power = self._getOutputPower()
        

        Laser.__init__(self, name, turnOn, **kwargs)

    def IsOn(self):
        _unilab_logger.debug("[UNILAB] PhoxxLaser.IsOn() called")
        return self.isOn

    def TurnOn(self):
        _unilab_logger.debug("[UNILAB] PhoxxLaser.TurnOn() called")
        ret, = self._query('LOn')
        if not ret == '>':
            raise RuntimeError('Error turning laser on')
        self.isOn = True

    def TurnOff(self):
        _unilab_logger.debug("[UNILAB] PhoxxLaser.TurnOff() called")
        ret, = self._query('LOf')
        if not ret == '>':
            raise RuntimeError('Error turning laser on')
    
        self.isOn = False

    def SetPower(self, power):
        _unilab_logger.debug("[UNILAB] PhoxxLaser.SetPower() called")
        if power < 0 or power > 1:
            raise RuntimeError('Error setting laser power: Power must be between 0 and 1')
        self.power = power
        
        p = int(0xFFF*power*self.power_fudge)
        
        ps = '%03X' % p
        
        ret, = self._query('SLP', ps)
        if not ret == '>':
            raise RuntimeError('Error setting laser power')

        #if self.isOn:
        #    self.TurnOn() #turning on actually sets power

    def _getOutputPower(self):
        _unilab_logger.debug("[UNILAB] PhoxxLaser._getOutputPower() called")
        pm = float(0xFFF)
        ret, = self._query('GLP')
        
        return int(ret, 16)/pm
        
    def _purge(self):
        _unilab_logger.debug("[UNILAB] PhoxxLaser._purge() called")
        try:
            while True:
                self.replyQueue.get_nowait()
        except:
            pass
    
    def _query(self, cmd, arg=None):
        _unilab_logger.debug("[UNILAB] PhoxxLaser._query() called")
        self._purge()
        s = cmd
        if arg:
            s = s + arg
            
        self.commandQueue.put('?%s\r' % s)
        
        cmr, vals = self._decodeResponse(self.replyQueue.get(timeout=3))
        
        if not cmd == cmr:
            raise RuntimeError('Queried with %s but got response to %s' % (cmd, cmr))
            
        return vals
    
    def _readline(self, ser):
        _unilab_logger.debug("[UNILAB] PhoxxLaser._readline() called")
        s = []
        c = ser.read().decode()
        while not c in ['', '\r']:
            s.append(c)
            c = ser.read().decode()
            
        return ''.join(s)
        
    def _poll(self):
        _unilab_logger.debug("[UNILAB] PhoxxLaser._poll() called")
        while self.doPoll:
            #print 'p'
            with serial.Serial(**self.ser_args) as ser:
                try:
                    cmd = self.commandQueue.get(False)
                    #print cmd
                    ser.write(cmd.encode())
                    ser.flush()
                    
                except Queue.Empty:
                    pass
                
                #wait a little for reply                
                time.sleep(.1)
                ret = self._readline(ser)
                #print(ret)
                
                if not ret == '':
                    #print ret
                    #process response - either a response or an ad-hoc message
                    if not ret.startswith('$'): #normal response
                        self.replyQueue.put(ret)
                    else: #adhoc
                        self._procAdHoc(ret)
                        #self.adhocQueue.put(ret)
                    
            time.sleep(.05)
                    
    def _decodeResponse(self, resp):
        _unilab_logger.debug("[UNILAB] PhoxxLaser._decodeResponse() called")
        cmd = resp[1:4]
        vals = resp[4:].split('\xA7')
        
        return cmd, vals
    
    def _procAdHoc(self, ret):
        _unilab_logger.debug("[UNILAB] PhoxxLaser._procAdHoc() called")
        cmd, vals = self._decodeResponse(ret)
        
        self.adHocVals[cmd] = vals
        
    def Close(self):
        _unilab_logger.debug("[UNILAB] PhoxxLaser.Close() called")
        print('Shutting down %s' % self.name)
        #try:
        self.TurnOff()
        time.sleep(.1)        
        #finally:
        self.doPoll = False
            #self.ser_port.close()
        
    def __del__(self):
        _unilab_logger.debug("[UNILAB] PhoxxLaser.__del__() called")
        self.Close()
        
    def GetOutputmW(self):
        _unilab_logger.debug("[UNILAB] PhoxxLaser.GetOutputmW() called")
        return float(self.adHocVals['MDP'][0])
        
    def GetStatusText(self):
        _unilab_logger.debug("[UNILAB] PhoxxLaser.GetStatusText() called")
        try:
            pow = self.GetOutputmW()
            return '%s laser power: %3.3f mW' % (self.name, pow)
        except:
            return '%s laser power: ERR' % self.name

    def GetPower(self):
        _unilab_logger.debug("[UNILAB] PhoxxLaser.GetPower() called")
        return self.power
        #return self._getOutputPower()

__all__ = ["PhoxxLaser"]
