"""
Auto-generated by Build Agent
Original: dmm.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.DMM")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Digitam Multimeter Driver for VXI instrument. Basically write for DMM6500/7510 Series. and 3446X Serise
import vxi11
from enum import Enum

class signal_type(Enum):
    DC = 0
    AC = 1
    dc = 0
    ac = 1

class resistance_method(Enum):
    two_wire=0
    four_wire=1

class DMM:

    def __init__(self,addr,model):
        print("[UNILAB] DMM.__init__() called", flush=True)
        self.addr=addr
        self.model=model
        self.instr=vxi11.Instrument(self.addr)
        self.instr.write("SYST:BEEP")
        print(self.instr.ask("*IDN?"))

    def voltage(self,mode:signal_type = signal_type.dc):
        _unilab_logger.debug("[UNILAB] DMM.voltage() called")
        if(mode==signal_type.dc):
            return float(self.instr.ask(":MEAS:VOLT:DC?"))
        if(mode==signal_type.ac):
            return float(self.instr.ask(":MEAS:VOLT:AC?"))

    def current(self,mode:signal_type = signal_type.dc):
        _unilab_logger.debug("[UNILAB] DMM.current() called")
        if(mode==signal_type.dc):
            return float(self.instr.ask(":MEAS:CURR:DC?"))
        if(mode==signal_type.ac):
            return float(self.instr.ask(":MEAS:CURR:AC?"))

    def resistance(self,mode:resistance_method=resistance_method.two_wire):
        _unilab_logger.debug("[UNILAB] DMM.resistance() called")
        if(mode==resistance_method.two_wire):
            return float(self.instr.ask(":MEAS:RES?"))
        if(mode==resistance_method.four_wire):
            return float(self.instr.ask(":MEAS:FRES?"))

if __name__=="__main__":
    my_dmm=DMM("192.168.2.128","34465A")

    # print(type(my_dmm.voltage(signal_type.ac)))
    # print(my_dmm.current(signal_type.dc))
    # print(my_dmm.resistance(resistance_method.two_wire))

__all__ = ["DMM"]
