"""
Auto-generated by Build Agent
Original: examples/3-class+debugPort/cobolt.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.CoboltLaser")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: examples
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

try:
    import serial as SP
except:
    exit("pyserial must be installed with: pip install pyserial")
import re

class CoboltDebugSerial:
    def __init__(self):
        self.outputBuffer = bytearray()
        self.lineEnding = b'\r'
        self.power = 0.1
        self.requestedPower = 0
        self.isOpen = True

    def open(self):
        if self.isOpen:
            raise IOError()
        else:
            self.isOpen = True

        return

    def close(self):
        if not self.isOpen:
            raise IOError()
        else:
            self.isOpen = False

        return

    def read(self, length) -> bytearray:
        data = bytearray()
        for i in range(0, length):
            if len(self.outputBuffer) > 0:
                byte = self.outputBuffer.pop(0)
                data.append(byte)
            else:
                raise CommunicationReadTimeout("Unable to read data")

        return data


    def write(self, data:bytearray) -> int :
        string = data.decode('utf-8')

        match = re.search("pa\\?", string)
        if match is not None:
            replyData = bytearray("{0}\r".format(self.power), encoding='utf-8')
            self.outputBuffer.extend(replyData)
            return len(data)

        match = re.search("p\\?", string)
        if match is not None:
            replyData = bytearray("{0}\r".format(self.requestedPower), encoding='utf-8')
            self.outputBuffer.extend(replyData)
            return len(data)

        match = re.search("p (\\d+\\.?\\d+)\r", string)
        if match is not None:
            self.power = match.groups()[0]
            return len(data)

        raise ValueError("Unknown command: {0}".format(data))

    def readline(self) -> bytearray:
        data = bytearray()
        byte = b''
        while byte != self.lineEnding:
            if len(self.outputBuffer) > 0:
                byte = self.outputBuffer.pop(0)
                data.append(byte)
            else:
                break

        return data

""" Class-oriented strategy to talk to the Cobolt
laser, change its power. See manual in ../manuals/ page 27"""

class CoboltLaser:

    def __init__(self, portName):
        print("[UNILAB] CoboltLaser.__init__() called", flush=True)
        """ portName : "COM1", "/dev/xxx", etc... 
        opens automatically on creation """
        self.port = None
        if portName == "debug":
            self.port = CoboltDebugSerial()
        else:
            self.port = SP.Serial(portName)

    def __del__(self):
        _unilab_logger.debug("[UNILAB] CoboltLaser.__del__() called")
        if self.port is not None:
            self.port.close()

    def setPower(self, powerInWatts):
        _unilab_logger.debug("[UNILAB] CoboltLaser.setPower() called")
        command = "p {0:0.3f}\r".format(powerInWatts)
        data = bytearray(command, "utf-8")
        self.port.write(data)
        reply = self.port.readline()

    def power(self):    
        _unilab_logger.debug("[UNILAB] CoboltLaser.power() called")
        self.port.write(b'pa?\r') 
        reply = self.port.readline()
        power = float(reply.decode())
        return power


if __name__ == "__main__":
    try:
        laser = CoboltLaser("COM1")
    except:
        laser = CoboltLaser("debug")

    laser.setPower(powerInWatts=0.1)
    print("Power is {0:0.3f} W".format(laser.power()))

    laser.setPower(powerInWatts=0.01)
    print("Power is {0:0.3f} W".format(laser.power()))

    laser.setPower(powerInWatts=0.001)
    print("Power is {0:0.3f} W".format(laser.power()))
    

__all__ = ["CoboltLaser"]
