"""
Auto-generated by Build Agent
Original: donkeycar/parts/serial_controller.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.SerialController")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: donkeycar
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))


"""
Scrits to read signals from Arduino and convert into steering and throttle outputs
Arduino input signal range: 0 to 200
Output range: -1.00 to 1.00
"""

import serial
import time

class SerialController:
    def __init__(self):
        print("[UNILAB] SerialController.__init__() called", flush=True)
        print("Starting Serial Controller")

        self.angle = 0.0
        self.throttle = 0.0
        self.mode = 'user'
        self.recording = False
        self.serial = serial.Serial('/dev/ttyS0', 115200, timeout=1) #Serial port - laptop: 'COM3', Arduino: '/dev/ttyACM0'


    def update(self):
        _unilab_logger.debug("[UNILAB] SerialController.update() called")
        # delay on startup to avoid crashing
        print("Warming Serial Controller")
        time.sleep(3)

        while True:
            line = str(self.serial.readline().decode()).strip('\n').strip('\r')
            output = line.split(", ")
            if len(output) == 2:
                if output[0].isnumeric() and output[1].isnumeric():
                    self.angle = (float(output[0])-1500)/500
                    self.throttle = (float(output[1])-1500)/500
                    if self.throttle > 0.01:
                        self.recording = True
                        print("Recording")
                    else:
                        self.recording = False
                    time.sleep(0.01)

    def run(self, img_arr=None):
        _unilab_logger.debug("[UNILAB] SerialController.run() called")
        return self.run_threaded()

    def run_threaded(self, img_arr=None):
        _unilab_logger.debug("[UNILAB] SerialController.run_threaded() called")
        #print("Signal:", self.angle, self.throttle)
        return self.angle, self.throttle, self.mode, self.recording

__all__ = ["SerialController"]
