"""
Auto-generated by Build Agent
Original: py4syn/epics/MythenClass.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.Mythen")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: py4syn, py4syn
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

"""
FILENAME... MythenClass.py
USAGE...    Python Class for EPICS Mythen
 
/*
 *      Original Author: Henrique Ferreira Canova
 *      Date: 10/03/2014
 */
"""

from epics import PV
from time import sleep
from py4syn.epics.StandardDevice import StandardDevice
from py4syn.epics.ICountable import ICountable

class Mythen(StandardDevice, ICountable):

    def finish(self, value, **kw):
        _unilab_logger.debug("[UNILAB] Mythen.finish() called")
        if value == 0:
            self.mythenfinish = True
        else:
            self.mythenfinish = False

    def __init__ (self,pvPrefix, mnemonic):
        print("[UNILAB] Mythen.__init__() called", flush=True)
        StandardDevice.__init__(self, mnemonic)
        self.pvAcquire = PV(pvPrefix + ":Acquire")
        self.pvTime = PV(pvPrefix + ":Time")
        self.pvDataRBV = PV(pvPrefix+ ":Data_RBV")
        self.pvAcquireRBV = PV(pvPrefix+":Acquire_RBV")
        self.pvAcquireRBV.add_callback(self.finish)
        self.pvSettings = PV(pvPrefix+":Settings") 
        self.pvFlatfield = PV(pvPrefix+":FlatfieldCorrection")
        self.pvFlatfieldRBV = PV(pvPrefix+":FlatfieldCorrection_RBV")
        self.pvFlip = PV(pvPrefix + ":FlipChannels")
        self.pvFlipRBV = PV(pvPrefix + ":FlipChannels_RBV")
 
        self.mythenfinish = (self.pvAcquireRBV.get() == 0)

    def changeTime(self,tempo):
        _unilab_logger.debug("[UNILAB] Mythen.changeTime() called")
        self.pvTime.put(tempo*10000000)
    
    def acquire(self):
        _unilab_logger.debug("[UNILAB] Mythen.acquire() called")
        self.pvAcquire.put(1)
        self.mythenfinish = False
        #sleep(0.1)
    
    def readout(self):
        _unilab_logger.debug("[UNILAB] Mythen.readout() called")
        return self.pvDataRBV.get()
        
    def waitFinish(self):
        _unilab_logger.debug("[UNILAB] Mythen.waitFinish() called")
        while not self.mythenfinish:
            sleep(0.001)
        
    def settings(self,settings=""):
        _unilab_logger.debug("[UNILAB] Mythen.settings() called")
        self.pvSettings.put(settings)

    def setFlatfield(self,bool):
        _unilab_logger.debug("[UNILAB] Mythen.setFlatfield() called")
        if ((bool != 0) and (bool != 1)):
            self.pvFlatfield.put(0)
        else:
            self.pvFlatfield.put(bool)

    def readFlatfield(self):
        _unilab_logger.debug("[UNILAB] Mythen.readFlatfield() called")
        return self.pvFlatfieldRBV.get()

    def setFlip(self,bool):
        _unilab_logger.debug("[UNILAB] Mythen.setFlip() called")
        if ((bool != 0) and (bool != 1)):
            self.pvFlip.put(1)
        else:
            self.pvFlip.put(bool)

    def readFlip(self):
        _unilab_logger.debug("[UNILAB] Mythen.readFlip() called")
        return self.pvFlipRBV.get()
        
    def getValue(self, **kwargs):
        _unilab_logger.debug("[UNILAB] Mythen.getValue() called")
        """
        Abstract method to get the current value of a countable device.

        Parameters
        ----------
        kwargs : value
            Where needed informations can be passed, e.g. select which channel must be read.

        Returns
        -------
        out : value
            Returns the current value of the device. Type of the value depends on device settings.
        """
        return self.readout()

    def setCountTime(self, t):
        _unilab_logger.debug("[UNILAB] Mythen.setCountTime() called")
        """
        Abstract method to set the count time of a countable target device.

        Parameters
        ----------
        t : value
            The target count time to be set.

        Returns
        -------
        out : None
        """
        self.changeTime(abs(t))

    def setPresetValue(self, channel, val):
        _unilab_logger.debug("[UNILAB] Mythen.setPresetValue() called")
        """
        Abstract method to set the preset count of a countable target device.

        Parameters
        ----------
        channel : `int`
            The monitor channel number
        val : `int`
            The preset value

        Returns
        -------
        out : None
        """
        self.changeTime(abs(val))
        
    def startCount(self):
        _unilab_logger.debug("[UNILAB] Mythen.startCount() called")
        """
        Abstract method trigger a count in a counter

        """
        self.acquire()
        
    def stopCount(self):
        _unilab_logger.debug("[UNILAB] Mythen.stopCount() called")
        """
        Abstract method stop a count in a counter

        """
        pass

    def canMonitor(self):
        _unilab_logger.debug("[UNILAB] Mythen.canMonitor() called")
        """
        Abstract method to check if the device can or cannot be used as monitor.

        Returns
        -------
        out : `bool`
        """        
        return True

    def canStopCount(self):
        _unilab_logger.debug("[UNILAB] Mythen.canStopCount() called")
        """
        Abstract method to check if the device can or cannot stop the count and return values.

        Returns
        -------
        out : `bool`
        """        
        return True
    
    
    def isCounting(self):
        _unilab_logger.debug("[UNILAB] Mythen.isCounting() called")
        """
        Abstract method to check if the device is counting or not.

        Returns
        -------
        out : `bool`
        """
        return (not self.mythenfinish)
    
    def wait(self):
        _unilab_logger.debug("[UNILAB] Mythen.wait() called")
        """
        Abstract method to wait for a count to finish.

        Returns
        -------
        out : `bool`
        """        
        self.waitFinish()
            

__all__ = ["Mythen"]
