"""
Auto-generated by Build Agent
Original: pycqed/instrument_drivers/meta_instrument/Current_Source_ER_88027.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.Current_Source_ER_88027")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: pycqed
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

import time

from qcodes.instrument.base import Instrument
from qcodes.utils import validators as vals


class Current_Source_ER_88027(Instrument):
    # Instruments will be a list of RemoteInstrument objects, which can be
    # given to a server on creation but not later on, so it needs to be
    # listed in shared_kwargs

    def __init__(self, name, Keithley_Vsource, Keithley_instr, **kwargs):
        print("[UNILAB] Current_Source_ER_88027.__init__() called", flush=True)
        super().__init__(name, **kwargs)
        self.keithley = Keithley_instr
        self.Vsource = Keithley_Vsource
        self.max_I = 10. #A
        self.max_V = 6.  #V

        Keithley_Vsource.seti(10e-3)
        self.add_parameter('I',
                           set_cmd=self._set_I,
                           get_cmd=self._get_I,
                           label='Current',
                           vals=vals.Numbers(max_value=self.max_I),
                           unit='A')



    def _get_I(self):
        _unilab_logger.debug("[UNILAB] Current_Source_ER_88027._get_I() called")
        return convert_I(self.keithley.amplitude())

    def _set_I(self,value):
        _unilab_logger.debug("[UNILAB] Current_Source_ER_88027._set_I() called")
        self.Vsource.setv(value)
        time.sleep(0.250)

    def seti(self,value):
        _unilab_logger.debug("[UNILAB] Current_Source_ER_88027.seti() called")
        self.I(value)

    def measurei(self):
        _unilab_logger.debug("[UNILAB] Current_Source_ER_88027.measurei() called")
        return self.I()

    def measureR(self):
        _unilab_logger.debug("[UNILAB] Current_Source_ER_88027.measureR() called")
        eps = 1e-4
        if abs(self.I()-0)>eps:
            return 0.3
        else:
            return 0.3


def convert_I(dacV):
    return dacV