"""
Auto-generated by Build Agent
Original: src/Logger-Accurion_EP4/libs/ipconnection.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.IPConnection")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

__author__ = 'Falk Ziegler'
__email__ = 'fz@accurion.com'
__maintainer__ = 'Falk Ziegler'

import socket
import struct
from functools import partial

def _pack(data, typecast=True):
    """
    WTF!
    """
    if not typecast:
        data = repr(data) if isinstance(data, str) else str(data)
    if isinstance(data, str):
        data = data.encode('utf-8')
    return struct.pack('>i', len(data)) + data


class IPConnection:
    """
    Class representing the IP connection into the Accurion apps.
    ToDo: Refactoring necessary -> Change protocol!
    """

    class GeneralErrorHandler(Exception):
        def __init__(self, message):
            print("[UNILAB] IPConnection.__init__() called", flush=True)
            self.message = message
        def __str__(self):
            _unilab_logger.debug("[UNILAB] IPConnection.__str__() called")
            return self.message

    def __init__(self, address, port):
        print("[UNILAB] IPConnection.__init__() called", flush=True)
        self.__sockets = {}
        self.__sandbox = {}
        self.__connect(address, port)

    def __enter__(self):
        _unilab_logger.debug("[UNILAB] IPConnection.__enter__() called")
        return self

    def __exit__(self, type, value, traceback):
        _unilab_logger.debug("[UNILAB] IPConnection.__exit__() called")
        self.close()

    def __connect(self, address, port):
        _unilab_logger.debug("[UNILAB] IPConnection.__connect() called")
        self.__address = (address, port)
        for i, name in enumerate(('STANDARD', 'INTERRUPT')):
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            try:
                s.settimeout(.1)
                s.connect(self.__address)
                self.__route('python+{0}@127.0.0.1:{1}'.format(name, 2345 + i), header=False, sync=False, sock=s)
                self.__sockets[name] = s
                if not i:
                    for name in self.__route('__init__', sock=s):
                        setattr(self, name, partial(self.__route, name, sock=s))
            except Exception as e:
                s.close()
                raise

    def __route(self, *args, header=True, sync=True, sock=None):
        _unilab_logger.debug("[UNILAB] IPConnection.__route() called")
        data = bytes()
        for i, arg in enumerate(args):
            if header and not i:
                # header + packed function name
                data += struct.pack('>IIbb', 123, 123, 1, 1) + _pack(arg)
            else:
                data += _pack(arg, typecast = False)
        # send packed data now
        data = sock.sendall(_pack(data))
        # data receive in case of synchronous message
        if sync:
            i = 0
            data = ''
            while True:
                try:
                    if not i:
                        payload = struct.unpack('>I', sock.recv(4))[0]
                    if i < payload:
                        data += sock.recv(1).decode('utf-8')
                        i += 1
                    else:
                        break
                except socket.timeout:
                    continue
            # we skip the complete header here
            status, source, data = eval(data[10:], {'__builtins__' : None}, self.__sandbox)
            if status:
                raise IPConnection.GeneralErrorHandler(source)
            return data

    def close(self):
        _unilab_logger.debug("[UNILAB] IPConnection.close() called")
        s = self.__sockets.get('INTERRUPT')
#        if s is not None:       #UNCOMMENTED BECAUSE OF INTERRUPT ISSUSE
#           self.__route('__close__', sync=False, sock=s)         #UNCOMMENTED BECAUSE OF INTERRUPT ISSUSE
        for name in list(self.__sockets.keys()):
            s = self.__sockets.pop(name)
            try:
                s.shutdown(socket.SHUT_RDWR)
                s.close()
            except:
                pass

__all__ = ["IPConnection"]
