"""
Auto-generated by Build Agent
Original: imswitch/imcontrol/model/interfaces/picamera.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\..*")
import sys as _sys
import types as _types

# 兼容性：部分上游框架（例如 lantz）在 import-time 强制加载 Qt（PyQt4/PySide1），
# 在 headless/现代 Python 环境中通常不存在这些绑定，会导致导入直接失败。
# 这里预注入一个最小的 `lantz.utils.qt` shim，避免触发其 Qt loader。
if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")

    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs):
                # 兼容 QObject(parent=...) 等调用
                return None

        @staticmethod
        def Signal(*_args, **_kwargs):
            return object()

        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn):
                return fn

            return _decorator

    _qt_mod.QtCore = _DummyQtCore

    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs):
            return super().__new__(cls)

        def __init__(self, *_args, **_kwargs):
            # 允许 Driver(...) 传参，不触发 object.__init__ 的 TypeError
            return None

    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

# Unilab 驱动调试日志
_unilab_logger = logging.getLogger("unilab.driver.CameraPiCam")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

# Vendored repo packages: imswitch, imswitch
import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

import numpy as np
import time
from imswitch.imcommon.model import initLogger
import socket
from imswitch.imcontrol.model.interfaces.restapicamera import RestPiCamera


class CameraPiCam:
    def __init__(self, host, port):
        print("[UNILAB] CameraPiCam.__init__() called", flush=True)
        super().__init__()
        self.__logger = initLogger(self, tryInheritParent=True)

        # URL for the remote camera
        self.host = host
        self.port = port

        # many to be purged
        self.model = "PiCamera"
        self.shape = (0, 0)

        # camera parameters
        self.blacklevel = 100
        self.exposure_time = 0
        self.analog_gain = 0

        self.SensorWidth = 640
        self.SensorHeight = 480
        # starting the camera thread

        self.camera = RestPiCamera(self.host, self.port)

    def start_live(self):
        _unilab_logger.debug("[UNILAB] CameraPiCam.start_live() called")
        # most likely the camera already runs
        pass #TODO:         self.camera.start_live()

    def stop_live(self):
        _unilab_logger.debug("[UNILAB] CameraPiCam.stop_live() called")
        pass         #TODO: self.camera.stop_live()

    def suspend_live(self):
        _unilab_logger.debug("[UNILAB] CameraPiCam.suspend_live() called")
        pass        #TODO: self.camera.stop_live()

    def prepare_live(self):
        _unilab_logger.debug("[UNILAB] CameraPiCam.prepare_live() called")
        pass

    def close(self):
        _unilab_logger.debug("[UNILAB] CameraPiCam.close() called")
        pass #TODO: self.camera.close()

    def set_exposure_time(self, exposure_time):
        _unilab_logger.debug("[UNILAB] CameraPiCam.set_exposure_time() called")
        self.exposure_time = exposure_time
        self.camera.set_exposuretime(self.exposure_time*1000)

    def set_analog_gain(self, analog_gain):
        _unilab_logger.debug("[UNILAB] CameraPiCam.set_analog_gain() called")
        self.analog_gain = analog_gain
        self.camera.set_iso(self.analog_gain)

    def set_blacklevel(self, blacklevel):
        _unilab_logger.debug("[UNILAB] CameraPiCam.set_blacklevel() called")
        pass

    def set_pixel_format(self, format):
        _unilab_logger.debug("[UNILAB] CameraPiCam.set_pixel_format() called")
        pass

    def getLast(self):
        _unilab_logger.debug("[UNILAB] CameraPiCam.getLast() called")
        # get frame and save
        return self.camera.get_preview()

    def getLastChunk(self):
        _unilab_logger.debug("[UNILAB] CameraPiCam.getLastChunk() called")
        return self.camera.get_snap()

    def setROI(self, hpos, vpos, hsize, vsize):
        _unilab_logger.debug("[UNILAB] CameraPiCam.setROI() called")
        hsize = max(hsize, 256)  # minimum ROI size
        vsize = max(vsize, 24)  # minimum ROI size
        pass
        # self.__logger.debug(
        #     f'{self.model}: setROI started with {hsize}x{vsize} at {hpos},{vpos}.'
        # )
        #self.camera.setROI(vpos, hpos, vsize, hsize)

    def setPropertyValue(self, property_name, property_value):
        _unilab_logger.debug("[UNILAB] CameraPiCam.setPropertyValue() called")
        # Check if the property exists.
        if property_name == "gain":
            self.set_analog_gain(property_value)
        elif property_name == "exposure":
            self.set_exposure_time(property_value)
        elif property_name == "blacklevel":
            self.set_blacklevel(property_value)
        else:
            self.__logger.warning(f'Property {property_name} does not exist')
            return False
        return property_value

    def getPropertyValue(self, property_name):
        _unilab_logger.debug("[UNILAB] CameraPiCam.getPropertyValue() called")
        # Check if the property exists.
        if property_name == "gain":
            property_value = self.camera.gain
        elif property_name == "exposure":
            property_value = self.camera.gain
        elif property_name == "blacklevel":
            property_value = self.camera.blacklevel
        elif property_name == "image_width":
            property_value = self.camera.SensorWidth
        elif property_name == "image_height":
            property_value = self.camera.SensorHeight
        else:
            self.__logger.warning(f'Property {property_name} does not exist')
            return False
        return property_value

    def openPropertiesGUI(self):
        _unilab_logger.debug("[UNILAB] CameraPiCam.openPropertiesGUI() called")
        pass

# Copyright (C) ImSwitch developers 2021
# This file is part of ImSwitch.
#
# ImSwitch is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ImSwitch is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

__all__ = ["CameraPiCam"]
