"""
Auto-generated by Build Agent
Original: https://github.com/yaq-project/yaqd-chemyx / yaqd_chemyx/_chemyx_fusion.py

[UNILAB DEBUG] 此驱动已注入调试日志
- 每个方法被调用时会打印日志
- 日志格式: [UNILAB] ClassName.method_name() called
- 查看日志: logging.getLogger("unilab.driver").setLevel(logging.DEBUG)
"""
from typing import Dict, Any, Optional
import logging
import warnings as _warnings
_warnings.filterwarnings("ignore", message=r"pkg_resources is deprecated as an API\\..*")
import sys as _sys
import types as _types

if "lantz.utils.qt" not in _sys.modules:
    _qt_mod = _types.ModuleType("lantz.utils.qt")
    class _DummyQtCore:
        class QObject:
            def __init__(self, *_args, **_kwargs): return None
        @staticmethod
        def Signal(*_args, **_kwargs): return object()
        @staticmethod
        def Slot(*_args, **_kwargs):
            def _decorator(fn): return fn
            return _decorator
    _qt_mod.QtCore = _DummyQtCore
    class _DummySuperQObject(_DummyQtCore.QObject):
        def __new__(cls, *_args, **_kwargs): return super().__new__(cls)
        def __init__(self, *_args, **_kwargs): return None
    _qt_mod.MetaQObject = type
    _qt_mod.SuperQObject = _DummySuperQObject
    _sys.modules["lantz.utils.qt"] = _qt_mod

_unilab_logger = logging.getLogger("unilab.driver.ChemyxFusion")
_unilab_logger.setLevel(logging.DEBUG)
if not _unilab_logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setFormatter(logging.Formatter("[%(asctime)s] %(message)s"))
    _unilab_logger.addHandler(_handler)

import sys as _sys
from pathlib import Path as _Path
_vendor_root = _Path(__file__).resolve().parent / "_vendor"
if _vendor_root.exists() and str(_vendor_root) not in _sys.path:
    _sys.path.insert(0, str(_vendor_root))

__all__ = ["ChemyxFusion"]

import asyncio
from typing import Dict, Any, List

from yaqd_core import IsDaemon, HasPosition, HasLimits, UsesSerial, UsesUart, aserial


class ChemyxFusion(IsDaemon):
    _kind = "chemyx-fusion"

    def __init__(self, name, config, config_filepath):
        super().__init__(name, config, config_filepath)
        self._ser = aserial.ASerial(
            self._config["serial_port"], baudrate=self._config["baud_rate"]
        )
        self._rate = None
        self._purging = False
        self._loop.create_task(self._get_rate())  # cache the rate later

    def close(self):
        self._ser.close()

    def direct_serial_write(self, message: bytes):
        self._ser.write(message)

    def get_rate(self) -> float:
        return self._rate

    def prime(self):
        # withdraw fully
        self.logger.info("Priming.")
        self._busy = True
        raise NotImplementedError

    def purge(self):
        # purge fully
        # this also implies that the new position is zero
        self.logger.info("Purging.")
        self._busy = True
        raise NotImplementedError

    def _set_position(self, position: float) -> None:
        amount_from_here = position - self._state["position"]
        self._ser.write(f"set volume {amount_from_here}".encode())
        self._ser.write("start".encode())

    def set_rate(self, rate):
        self._ser.write(f"set rate {rate}".encode())

    async def update_state(self):
        while True:
            out = self._ser.write_then_read("view parameter")
            print(out)
